### ISSUE TITLE
include or remove fedoidc dependency

### ISSUE THREAD

**Issue by zandbelt** [openid-certification/oidctest#1]
Right now `oidctest` depends on `fedoidc`:
```
Installed /usr/local/lib/python3.5/dist-packages/oidctest-0.7.0-py3.5.egg
Processing dependencies for oidctest==0.7.0
Searching for fedoidc
Reading https://pypi.python.org/simple/fedoidc/
Couldn't find index page for 'fedoidc' (maybe misspelled?)
Scanning index of all packages (this may take a while)
Reading https://pypi.python.org/simple/
No local packages or download links found for fedoidc
error: Could not find suitable distribution for Requirement.parse('fedoidc')
```
So, either the `oidc-certification` repository needs to fork `fedoidc` too or it needs to be separated out.

**Comment by rohe** [comment]
I'll make a pypi distribution of fedoidc. I don't think we want a fork of fedoidc in openid-cerification.

**Comment by zandbelt** [comment]
sounds good although I don't see why there would need to be a dependency on fedoic.. I would expect the dependency to be the other way around

**Comment by rohe** [comment]
There are functionality in fedoidc that doesn't exit in pyoidc that is used in oidctest.
It could possibly be moved to oidctest or to a module of it's own.

**Comment by zandbelt** [comment]
My vote goes to moving it to oidctest ;-) !

**Comment by rohe** [comment]
I absolutely hate having the same code in two separate modules. And if I where to copy it to oidctest I still would have to keep it in fedoidc because I could not import oidctest to fedoidc.
So the only solution then would to make it a module of its own.

**Comment by zandbelt** [comment]
Ah, I understand; then I think keeping it in fedoidc and make a pypi distribution/release of it works for me!

**Comment by zandbelt** [comment]
on 2nd thought: what about moving that code to otest?

**Comment by rohe** [comment]
Same problem. 
I'll have a look at breaking it out of fedoidc into its own module.
When I had my ITS group we had a module with nice tools/functions that we used in many project but didn't want to have separate copies of all over the map. Could do something similar here.

**Comment by rohe** [comment]
I think we can close this for now.
We may revisit it in the future but right now we'll have a dependency on fedoidc.
