### ISSUE TITLE
Add response_mode=form_post test returning an error

### ISSUE THREAD

**Issue by selfissued** [openid-certification/oidctest#101]
On the 1-Nov-18 call, @panva suggested that we produce a variant of the OP-prompt-none-NotLoggedIn test response_mode=form_post so that we can verify that errors are returned according to the response mode as well.

Also, to make these tests easier to find for people doing certifications, could we move both the existing "OP-Response-form_post" test and this new test (which I'd call OP-Error-form_post) into a new test category?  Currently the existing test is in the category "Response Type & Response Mode".  I'd split this category into two, so that there is a "Response Type" category and a "Response Mode" category.

**Comment by selfissued** [comment]
I just assigned this to @rohe .  If you'd rather do it @zandbelt , then feel free to change the assignment.

**Comment by rohe** [comment]
Done, added a test.

**Comment by panva** [comment]
> Done, added a test.

Isn't "Note" missing in the sequence to make sure the testers clear the OP session cookies?

**Comment by selfissued** [comment]
Roland, can you add a note like the one in the test OP-prompt-none-NotLoggedIn that the new test was based on?

**Comment by panva** [comment]
See https://github.com/rohe/otest/pull/5 and https://github.com/rohe/oidctest/pull/99 for the test "Note" added and category split.

**Comment by rohe** [comment]
Done

**Comment by zandbelt** [comment]
deployed as part of OP version 2.1.2 now; the test is called `OP-Response-form_post-Error`
