### ISSUE TITLE
OP-Rotation-OP-Sig appearing when Dynamic Registration not true

### ISSUE THREAD

**Issue by selfissued** [openid-certification/oidctest#102]
As we discussed in the thread "2 questions on certification testing", OP-Rotation-OP-Sig shouldn't appear in the OP test list unless Dynamic Registration is configured.  Roland had earlier made a fix to remove OP-Rotation-OP-Sig and OP-request_uri-Support from being displayed by default.

However, I'm doing some testing for Microsoft and noticed that OP-Rotation-OP-Sig still showing up for configurations using .well-known/openid-configuration (Dynamic Discovery).  @rohe or @zandbelt - could you please change this logic so that it appears when Dynamic Registration is true, rather than when Dynamic Discovery is true?

Thanks.

**Comment by zandbelt** [comment]
I created a PR to Roland's upstream repo for this https://github.com/rohe/oidctest/pull/98

**Comment by rohe** [comment]
Merged PR

**Comment by zandbelt** [comment]
deployed as part of OP version 2.1.2 now
