### ISSUE TITLE
The test OP-IDToken-SigEnc does not return any result

### ISSUE THREAD

**Issue by Spomky** [openid-certification/oidctest#108]
Hi,

When I try to test my IDP again the test named `OP-IDToken-SigEnc`, I can see in my logs that the communication between the test instance and my IDP is correctly established, but no result is returned.

I can see the following requests:

* GET https://oidc.spomky-labs.com/.well-known/webfinger?rel=http%3A%2F%2Fopenid.net%2Fspecs%2Fconnect%2F1.0%2Fissuer&resource=acct%3Ajohn.1%40oidc.spomky-labs.com (200 HTTP Response)
* GET https://oidc.spomky-labs.com/.well-known/openid-configuration (200 HTTP Response)
* POST https://oidc.spomky-labs.com/client/management (201 HTTP Response)
* GET https://oidc.spomky-labs.com/authorize?client_id=fcf2ee53f1d42e9e3dbabb45862addb9c7d7968812809d153ca6b8552da82626&nonce=6ppf07Uw0XjtTZSd&redirect_uri=https%3A%2F%2Fop.certification.openid.net%3A61311%2Fauthz_cb&response_type=code%20id_token%20token&scope=openid&state=Dr0aVVnsNMk9QzuF (200 HTTP Response)
* POST https://oidc.spomky-labs.com/authorize?client_id=fcf2ee53f1d42e9e3dbabb45862addb9c7d7968812809d153ca6b8552da82626&nonce=6ppf07Uw0XjtTZSd&redirect_uri=https%3A%2F%2Fop.certification.openid.net%3A61311%2Fauthz_cb&response_type=code%20id_token%20token&scope=openid&state=Dr0aVVnsNMk9QzuF (302 HTTP Response -- Client granted by the resource owner)
* POST https://oidc.spomky-labs.com/token/get (200 HTTP Response)
* GET https://oidc.spomky-labs.com/public.jwkset (200 HTTP Response)

I have no clue to understand why the test stops.
Do you have any idea?

**Comment by Spomky** [comment]
Test instance is https://op.certification.openid.net:61311
You can log in using username `john.1` and password `secret`

**Comment by zandbelt** [comment]
The `id_token` in the response is lacking the `at_hash` property which is required for the `code id_token token` flow that you're executing; only `c_hash` is present in the `id_token`. The lack of a user facing error message from the test suite is already reported in https://github.com/openid-certification/oidctest/issues/95 and followup will happen in that ticket.

**Comment by Spomky** [comment]
Many thanks.

I will fix it ASAP and test again.

Regards.
