### ISSUE TITLE
OP-request-Unsigned & OP-request_uri-Unsigned show incomplete when error request_not_supported is returned

### ISSUE THREAD

**Issue by aeneasr** [openid-certification/oidctest#109]
As far as I understand, tests `OP-request-Unsigned` & `OP-request_uri-Unsigned` should either expect a success response or, in the case where `request` and `request_uri` are not supported, expect the `request_not_supported` / `request_uri_not_supported` error. The second output should be expected even more so, if the discovery process yields `false` for `request_parameter_supported` and `request_uri_parameter_supported`.

The assertion can be found [here](https://github.com/openid-certification/oidctest/blob/a0c90aed0e79efb0a2751d74823e9b80c874cdd8/tests/oidc_flows.yaml#L2057) and [here](https://github.com/openid-certification/oidctest/blob/a0c90aed0e79efb0a2751d74823e9b80c874cdd8/tests/oidc_flows.yaml#L2185).

However, for the `code` response type, the tests show an incomplete status / partial result:

## OP-request-Unsigned

![image](https://user-images.githubusercontent.com/3372410/41506570-78adff9e-7220-11e8-8fc4-ed387da7b1c0.png)

## OP-request_uri-Unsigned

![image](https://user-images.githubusercontent.com/3372410/41506571-80abfade-7220-11e8-980f-8490175fad90.png)

## Hybrid flows

When the response type is one of the hybrid flows (e.g. `code token`), then the test doesn't even show as being processed at all, despite the request being propagated (as far as I can tell) properly (an error is sent back as part of the implicit response):

![errrequri2](https://user-images.githubusercontent.com/3372410/41506610-6a1a5de6-7221-11e8-9de7-8f06bec2decc.gif)

I'm not sure if any of this is intentional or not, but as far as my understanding goes (and following the descriptions from the UI), it seems like these parameters are not required to pass but either expected to fail with that exact error, or pass with the parameters provided.

**Comment by panva** [comment]
Related to #92 and #105

**Comment by arekkas** [comment]
Thank you for the swift reply. I looked at those issues but apparently missed the last part:

> Additionally, the OP-request_uri-Support and OP-request-Support tests should check for authorization failure errors request_not_supported and request_uri_not_supported when a given support is not declared by the discovery endpoint.

How would that affect the certification process? Especially regarding the tests that do not even show a test result (hence, I can not submit it)? Does that mean that, if request/request_uri are not supported, I can not get the dynamic client registration with hybrid flows certified?

**Comment by panva** [comment]
@selfissued is best to answer the submission question, I’m not sure if the profile allows to not support request/_uri

**Comment by selfissued** [comment]
Per the profile definitions at http://openid.net/wordpress-content/uploads/2016/12/OpenID-Connect-Conformance-Profiles.pdf in the "request_uri Request Parameter" section, you must support request_uri to be certified for the Dynamic profile.  Returning the "not supported" error is not sufficient.

**Comment by rohe** [comment]
Pushed some changes to oidctest and otest. Will hopefully sort things out.

**Comment by zandbelt** [comment]
deployed to production now as part of OP version 2.1.2; please confirm

**Comment by arekkas** [comment]
Since the bug has been fixed in my software, I can't re-run the same test, but I'll try in the next days to roll back to the version that was affected by this in order to confirm!

**Comment by zandbelt** [comment]
we'll assume this has been fixed; if not this can be re-opened or a new issue can be created
