### ISSUE TITLE
links for mod_auth_openidc on the RP test pages are outdated and return HTTP 500

### ISSUE THREAD

**Issue by zandbelt** [openid-certification/oidctest#11]
The RP test documentation at http://openid.net/certification/rp_testing/ lists links that result in errors.
Clicking:
https://rp.certification.openid.net:8080/mod_auth_openidc/rp-response_type-code
And selecting then the "code" profile will take you to https://rp.certification.openid.net:8080/mod_auth_openidc/list?profile=C
which will result in the following error in the browser:
````
500 Internal Server Error

The server encountered an unexpected condition which prevented it from fulfilling the request.

Traceback (most recent call last):
  File "/home/oictest/.local/lib/python3.5/site-packages/cherrypy/_cprequest.py", line 642, in respond
    self.get_resource(path_info)
  File "/home/oictest/.local/lib/python3.5/site-packages/cherrypy/_cprequest.py", line 760, in get_resource
    dispatch(path)
  File "/home/oictest/.local/lib/python3.5/site-packages/cherrypy/_cpdispatch.py", line 294, in __call__
    func, vpath = self.find_handler(path_info)
  File "/home/oictest/.local/lib/python3.5/site-packages/cherrypy/_cpdispatch.py", line 357, in find_handler
    subnode = dispatch(vpath=iternames)
  File "/usr/local/lib/python3.5/dist-packages/oidctest-0.7.0-py3.5.egg/oidctest/cp/op.py", line 376, in _cp_dispatch
    self.flows[test_id]
  File "/usr/local/lib/python3.5/dist-packages/otest-0.7.0-py3.5.egg/otest/flow.py", line 79, in __getitem__
    fp = open(fname, 'r')
FileNotFoundError: [Errno 2] No such file or directory: '/home/oictest/oidf/oidc_cp_rplib/flows/list.json'
````

It looks like doing the same for more recent clients still works i.e. doesn't take you to a non-existing `mod_auth_openidc/list?profile=C` page but to `list?profile=C`.

Perhaps the code changed and this client registration is obsolete?

**Comment by selfissued** [comment]
The instructions include links to actual log entries so people can see examples of them.  We used mod_auth_openidc logs because they were some of the first available.  I'll look into updating the example links after finish some things I have to do for EIC.

**Comment by zandbelt** [comment]
After closer inspection, only two small changes are required:

1. 

> For instance, the issuer used when testing the “code” response_type for the Apache OpenID Connect RP is:
> 
> https://rp.certification.openid.net:8080/mod_auth_openidc/rp-response_type-code
> 

change the HTML code so that the issuer value no longer represents a clickable link but rather consists of non-clickable text only; it is this issuer value that leads to errors further down the road when clicked and an issuer value shouldn't be clickable anyway (unlike its derived Discovery document location further down in the text)

2.

> An actual example server log entry path is:
> 
> https://rp.certification.openid.net:8080/log/mod_auth_openidc/rp-response_type-code
> 

add a `.txt` extension postfix to this link/filename so that it actually references a log file. (the extension naming of log files was changed a while ago)

**Comment by zandbelt** [comment]
Actually the problem was on my side: the request URI could not correctly been resolved. I'm turning this into an enhancement request since it would be highly convenient to improve error logging around this. (it used to be better as I recall, where I could actually see resolving the request URI failing with a proper error message)

**Comment by zandbelt** [comment]
@selfissued  could you take a look, especially at the last comment https://github.com/openid-certification/oidctest/issues/11#issuecomment-299823353 ?
