### ISSUE TITLE
Add additional redirect_uri requirement to OP form post testing instructions

### ISSUE THREAD

**Issue by selfissued** [openid-certification/oidctest#112]
We need to add the need to add the additional /authz_post redirect_uri values to the testing instructions for the form post response mode.  I think it need to go in these places:

1. In the tool tip help next to the `redirect_uris` form value in the provider configuration page at `https://new-op.certification.openid.net:60000/action/update`.

2. In the tool tip help next to the `form_post` check box in the provider configuration page at `https://new-op.certification.openid.net:60000/action/update`.

3. Ideally, when `form_post` `True` is checked, the page should somehow alert the user that `https://new-op.certification.openid.net:60019/authz_post` must be added to the redirect_uris for the client.

4. Ideally, when `form_post` is checked at `https://new-op.certification.openid.net:60019/pedit`, the page should remind the tester that `https://new-op.certification.openid.net:60019/authz_post` must be added to the set of redirect_uris for the client.

5. This should be described at `http://openid.net/certification/testing/`.  I'll do this one.

Is there anyplace else that this information should also be?

**Comment by zandbelt** [comment]
deployed on test & production now as part of 2.1.3

NB: implementing 3 was not possible without severe impact to the way the GUI is built so I've left it at a tooltip
