### ISSUE TITLE
ID Token related tests fail with fatal server error after successful `OP-Rotation-OP-Sig`

### ISSUE THREAD

**Issue by aeneasr** [openid-certification/oidctest#113]
I am running a test profile for `code` with `sign=true`, dynamic client registration, and oidc discovery:

![image](https://user-images.githubusercontent.com/3372410/41807977-69049e70-76d7-11e8-9706-7830a7fcecc3.png)

All tests pass if I run the `OP-Rotation-RP-Sig` test last. If I run the `OP-Rotation-RP-Sig` first, all other tests which validate the ID Token (**I think**) fail with an "internal server error". There is no way to get a stack trace as the log seems to be empty. Here's an example of such a test failing:

![servererroidc](https://user-images.githubusercontent.com/3372410/41807925-ae7533c6-76d6-11e8-9228-03585eaea4f5.gif)

**Comment by arekkas** [comment]
The error seems to be related to an invalid signature, it would be nice if a stack trace were available when that happens, so it's easier to debug!

**Comment by zandbelt** [comment]
possibly addressed in https://github.com/openid-certification/otest/commit/5ca51871b9212e581d9e6a6bfd62d568c595a718

**Comment by selfissued** [comment]
@arekkas please retry.  The 500 error should be fixed now.

**Comment by zandbelt** [comment]
we'll assume that this has been fixed; if not this can be re-opened or a new issue can be created
