### ISSUE TITLE
500 Internal Server Error

### ISSUE THREAD

**Issue by selfissued** [openid-certification/oidctest#114]
Trying to use the test OP-IDToken-C-Signature at https://op.certification.openid.net:60046/ logging in as mbj@shiungtrial.onmicrosoft.com results in a 500 Internal Server Error and no log being generated.  Yes, the OP is incorrect in that it doesn't return token_type or access_token values.  But this test used to at least generate a log with comprehensible error messages.  It needs to again.

**Comment by zandbelt** [comment]
addressed in https://github.com/openid-certification/otest/commit/5ca51871b9212e581d9e6a6bfd62d568c595a718, deployed on `new-op` for testing

**Comment by selfissued** [comment]
I have verified that the 500 error is fixed in new-op.  https://new-op.certification.openid.net:60021/test_info/OP-IDToken-C-Signature is a log that would have resulted in a 500 in production.  Please deploy to production.  Thanks.

**Comment by selfissued** [comment]
This appears to be fixed now.
