### ISSUE TITLE
add form_post response_mode error test for RP

### ISSUE THREAD

**Issue by zandbelt** [openid-certification/oidctest#119]
We need an RP test where the RP handles an error response sent via form post.  This would correspond to the OP test OP-Response-form_post-Error.

**Comment by selfissued** [comment]
We should do this before we take the Form Post profiles out of pilot mode.

**Comment by zandbelt** [comment]
ETA: end of september

**Comment by zandbelt** [comment]
https://github.com/zmartzone/oidctest/commit/6052c57174316ec0029336ba976220ccf4603e0c

actually pyoidc could/should be improved to handle sending errors with form_post...

**Comment by zandbelt** [comment]
merged into rohe upstream https://github.com/rohe/oidctest/pull/110

**Comment by panva** [comment]
i just gave this a test

1) the test description should state the conditions HOW to trigger this error, (max_age, prompt)
2) when actually doing so i get a 500 from the suites authorization endpoint with the text `Unrecoverable error in the server.` response.

**Comment by zandbelt** [comment]
can you provide the stacktrace here?

**Comment by panva** [comment]
there's nothing returned by the suite other than `Unrecoverable error in the server.`

**Comment by panva** [comment]
- dynamically created client
- hit https://rp.certification.openid.net:8080/node-openid-client/rp-response_mode-form_post-error/authorization?client_id=gVYZkxSWE5GF&scope=openid&response_type=code&response_mode=form_post&redirect_uri=https%3A%2F%2Fnode-openid-client.dev%2Fcb&nonce=0.16329591997219817&prompt=none&max_age=0

**Comment by zandbelt** [comment]
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/CherryPy-8.9.1-py3.6.egg/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/usr/local/lib/python3.6/dist-packages/CherryPy-8.9.1-py3.6.egg/cherrypy/lib/encoding.py", line 220, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/CherryPy-8.9.1-py3.6.egg/cherrypy/_cpdispatch.py", line 60, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.6/dist-packages/oidctest-0.7.3-py3.6.egg/oidctest/cp/op.py", line 216, in index
    resp = op.authorization_endpoint(kwargs)
  File "/usr/local/lib/python3.6/dist-packages/oidctest-0.7.3-py3.6.egg/oidctest/rp/provider.py", line 451, in authorization_endpoint
    "state": _req['state']
KeyError: 'state'
```
This should be solved in another issue, but could you add state?

**Comment by panva** [comment]
it works when `state` is added

**Comment by zandbelt** [comment]
let's tackle the state thing in a different issue then

**Comment by panva** [comment]
and the description to aid testers

**Comment by panva** [comment]
openid-client-conformance-tests [test](https://github.com/panva/openid-client-conformance-tests/commit/cfe0f536cde06314cdfe2fcb3cf8db30c786c69d)

**Comment by zandbelt** [comment]
closing this, improving in #132
