### ISSUE TITLE
OP-Registration-Sector-Bad - doesn't send pairwise subject_type

### ISSUE THREAD

**Issue by panva** [openid-certification/oidctest#122]
As the title says, the test does not send subject_type as `pairwise` in the registration request. An OP might ignore the sector_identifier_uri in that case (since it has no use for that property), signalling so by not sending it back in the registration response.

I propose that one of the following changes are made

1) ~(still without sending pairwise) the test passes if the sector_identifier_uri is not received in the registration response (it was ignored)~
2) subject_type=pairwise is sent

**Comment by selfissued** [comment]
We need to add "subject_type": "pairwise" to the registration request sent by the test tool for this test.

**Comment by rohe** [comment]
I've uploaded a new version that fixes this.

**Comment by zandbelt** [comment]
released as part of OP version 2.1.5, deployed on September 28
