### ISSUE TITLE
true / false for field gives wrong type of value for "email_verified"

### ISSUE THREAD

**Issue by TheIdentityHub** [openid-certification/oidctest#123]
Hello,

We are trying to certify our openid connect implementation.

We always end up with this error:

AccessToken:OP-UserInfo-Body: status=ERROR, message="false", wrong type of value for "email_verified"

We tried

“email_verified”: false => according to spec.
“email_verified”: False
“email_verified”: 0
“email_verified”: “0”
“email_verified”: “False”
“email_verified”: “false”

It always fails.

What could be the issue?

Regards
Hannes

**Comment by zandbelt** [comment]
discussion pending on the list; seems like there actually wasn't a real JSON boolean provided
