### ISSUE TITLE
OP-IDToken-C-Signature failing with NoSuitableSigningKeys

### ISSUE THREAD

**Issue by bbulczynski** [openid-certification/oidctest#127]
Hi,
I'm testing ORY Hydra based solution and keep getting:

```
  File "/usr/local/lib/python3.5/dist-packages/pyjwkest-1.4.0-py3.5.egg/jwkest/jws.py", line 565, in verify_compact_verbose
    "No key with kid: %s" % (self["kid"]))
```

Have checked that this kid is available publicly under .well-known/jwks.json and IdToken was signed with it correctly (verified by jwt.io)
IdToken header contains proper kid value aligned with jwt.json content.

Any suggestion what should i check next?
Thanks in advance!

**Comment by bbulczynski** [comment]
BTW worked with Dynamic Discovery.

**Comment by zandbelt** [comment]
Sorry for coming back to this only now, is this still relevant?

**Comment by selfissued** [comment]
Closing until repro information is supplied, at which point this can be reopened and investigated.
