### ISSUE TITLE
OP-nonce-NoReq-noncode in code+token

### ISSUE THREAD

**Issue by panva** [openid-certification/oidctest#14]
While it is clear that nonce is required for I, IT, CI and CIT, for CT this is debatable since no ID Token is returned from the authorization endpoint. 

After a little digging it looks like the debate was already had in [connect/issues/972](https://bitbucket.org/openid/connect/issues/972/nonce-requirement-in-hybrid-auth-request).

We should enable this test for CT.

**Comment by zandbelt** [comment]
This was now merged in cc8b59b012d70292d3967d2c959a4d092ab3cda5 and pushed to rp.certification.openid.net; can you confirm?

**Comment by panva** [comment]
but, this is an op test - can't find the test in neither op or new-op

**Comment by zandbelt** [comment]
duh, hold on..

**Comment by panva** [comment]
confirmed

**Comment by selfissued** [comment]
Per the working group decision to not require a nonce request parameter for the "code token" response type, we should remove the test OP-nonce-NoReq-noncode from the "code token" tests.

**Comment by zandbelt** [comment]
Pasting from the discussion at rohe's repo:

> https://bitbucket.org/openid/connect/issues/1052 was closed but the friendly dissuasion around it resulted in https://bitbucket.org/openid/connect/issues/972 being reopened and resolved with a different and now correct outcome. As such, I'd respectfully request that this issue be addressed so as to not have a test that requires the nonce when the response type is 'code token'.

We'll work on a new release asap.

**Comment by b---c** [comment]
"dissuasion" should have been "discussion"

**Comment by zandbelt** [comment]
that's rolled out now on production (and test) as part of release 2.2.0
