### ISSUE TITLE
Issue in OP-nonce-NoReq-noncode in implicit flow test

### ISSUE THREAD

**Issue by prasannaramachandran** [openid-certification/oidctest#144]
At the start of this test, it says - 

""This test should result in the OpenID Provider displaying an error message in your user agent. You should ignore the status of this test in the test tool, since it will be incomplete. You must submit a screen shot of the error shown as part of your certification application."

However, it is not actually the Provider displaying the error message but rather the RP that displays the error response that the OP produced. 

Opening this ticket as per my email conversation with Hans Zandbelt

**Comment by zandbelt** [comment]
This appears to be a copy/paste error:
```
$ grep -l "OpenID Provider displaying an error message" *
OP-nonce-NoReq-noncode.json
OP-redirect_uri-Missing.json
OP-redirect_uri-MissingOK.json
OP-redirect_uri-NotReg.json
OP-redirect_uri-Query-Added.json
OP-redirect_uri-Query-Mismatch.json
```
The other tests are about issues with the Redirect URI in which case the OP should indeed display the error according to https://tools.ietf.org/html/rfc6749#section-4.1.2.1:

> 4.1.2.1.  Error Response
> 
>    If the request fails due to a missing, invalid, or mismatching
>    redirection URI, or if the client identifier is missing or invalid,
>    the authorization server SHOULD inform the resource owner of the
>    error and MUST NOT automatically redirect the user-agent to the
>    invalid redirection URI.

And it states about other classes of errors:

>    If the resource owner denies the access request or if the request
>    fails for reasons other than a missing or invalid redirection URI,
>    the authorization server informs the client by adding the following
>    parameters to the query component of the redirection URI using the
>    "application/x-www-form-urlencoded" format, per Appendix B:

So the description for `OP-nonce-NoReq-noncode` should indeed mention that the RP should display the error.

**Comment by zandbelt** [comment]
Let's review and confirm cfe69cd on the next certification call.

**Comment by zandbelt** [comment]
This was deemed the correct approach on our call today.

**Comment by zandbelt** [comment]
this was deployed just now as part of OP 2.2.1 https://github.com/openid-certification/oidctest/releases/tag/v1.2.0
