### ISSUE TITLE
Wrong type comparison in tests

### ISSUE THREAD

**Issue by tpazderka** [openid-certification/oidctest#145]
Code in [`oidctst.op.func.check_support`](https://github.com/openid-certification/oidctest/blob/master/src/oidctest/op/func.py#L124) is doing a wrong comparison of types. It is using `==` instead of using `issubclass`.

The simple comparison tests starts failing once pyoidc drops support for python 2. The returned type will be simple `str` and not a `past.types.basestring.basestring`.

Anyway `basestring` from `future` library doesn't seem to be properly subclassed as it can only be compared to instances. This is not true for `six.string_types`, so I would recommend using those.

**Comment by zandbelt** [comment]
this was deployed just now as part of OP 2.2.1 https://github.com/openid-certification/oidctest/releases/tag/v1.2.0
