### ISSUE TITLE
local test PASSED but online test failed?

### ISSUE THREAD

**Issue by bitman694** [openid-certification/oidctest#147]
We have built a local op_test in a docker and we use it to test our OP.
We got PASSED results offline but when we test online in the web: https://op.certification.openid.net , (e.g. test-id is OP-Response-id_token), we failed and no logs shown.
We guess it's related with the "sig.key" and the value of the kid in JWT headers.
We found in the source code(pyjwkest-1.4.0-py3.5.egg/jwkest/jwk.py  line 368) that kid is a hash related with the /oidf/oidc_op/keys/sig.key
So, we wonder two things:
    1. Why our OP passed local op_test and failed online?
    2. How to set the kid value? Is it should be set in the OP configuration in the online op_test?

Our OP config:
      Implicit (id_token)
      Static webfinger
      Static discovery
      Static registration
      Crypto support ['sign']

Thanks.

**Comment by zandbelt** [comment]
Thanks for reporting; it may have to do with SSL certificate checking on your OP endpoints; can you point us to the instance on op.certification.openid.net that you referred to?

**Comment by bitman694** [comment]
@zandbelt 
Sure,
it's https://op.certification.openid.net:61587/

**Comment by zandbelt** [comment]
You have used a local IP address for your OP:
```
2019-03-05 08:34:39,379 oic.utils.keyio:DEBUG loading keys for issuer: http://192.168.151.141
2019-03-05 08:34:39,380 oic.utils.keyio:DEBUG pcr: {'issuer': 'http://192.168.151.141', 'authorization_endpoint': 'http://192.168.151.141/login', 'jwks_uri': 'http://192.168.151.141/jwks', 'response_types_supported': ['id_token'], 'subject_types_supported': ['public'], 'id_token_signing_alg_values_supported': ['RS256']}

```
you have to change this to something that's publicly accessible to use the public - official - instance of the certification suite.

**Comment by bitman694** [comment]
@zandbelt we build a new config https://op.certification.openid.net:61592/
the issuer is http://159.226.94.152
but it's not OK.

**Comment by zandbelt** [comment]
Could you explain what is wrong?

**Comment by bitman694** [comment]
@zandbelt I'll mail to you for more details later.

**Comment by bitman694** [comment]
@zandbelt 
In the OP config on op_test, our issuer is http://159.226.94.152
But in our OP source code, it is http://159.226.94.152/
We found it recorded in the /server_log (oic/oic/message.py  line 288).
But the op_test doesn't show the error.

Thanks !
