### ISSUE TITLE
OP-OAuth-2nd fails with PARTIAL RESULT

### ISSUE THREAD

**Issue by SebAubin** [openid-certification/oidctest#149]
Hi, 

i'm trying to execute the **OP-OAuth-2nd** test and it fails even though i'm returning a **400** **BAD_REQUEST** with a JSON body like: 

`{'error': 'invalid_grant'}`

The result I get is: 

![image](https://user-images.githubusercontent.com/11835253/53913469-65f67c00-4029-11e9-9340-8b16263893f0.png)

Do you know what i'm doing wrong?

Thank you

**Comment by zandbelt** [comment]
Could you test against the public instance of the test suite at https://op.certification.openid.net:60000 or provide the relevant `op_test.log` parts?

**Comment by SebAubin** [comment]
Hi, i've tried with the public instance and I get the same result.

![screen shot 2019-03-07 at 08 00 24](https://user-images.githubusercontent.com/11835253/53958580-6afe0e80-40af-11e9-9f4f-4ce5b1658de7.png)

**Comment by zandbelt** [comment]
Your OP seems to return the 400 for the first time the code is used. It should only do this for the 2nd time that the same code is used by the test suite.

**Comment by SebAubin** [comment]
This is it! Thank you!
