### ISSUE TITLE
OP-BackChannel-RpInitLogout-no-id_token_hint

### ISSUE THREAD

**Issue by panva** [openid-certification/oidctest#157]
Status: 🔴 

`exception_trace` is returned as text to the browser after confirming the prompt.

The description should read `the request is missing id_token_hint`

According to the latest agreement on the oidc issue tracker the only correct behaviour here is an error rendered by the OP.

**Comment by rohe** [comment]
A link to the tracker issue you're talking about would be nice.

**Comment by panva** [comment]
Sorry, here you go - [link](https://bitbucket.org/openid/connect/issues/1032/rp-initiated-logout-proposal-for-client_id#comment-51373773)
