### ISSUE TITLE
add a version number to the list of certified implementations

### ISSUE THREAD

**Issue by zandbelt** [openid-certification/oidctest#16]
As we start to version the codebase and server instance, the list of registered self-certified implementations should mention against which version of the test suite certification was done.

**Comment by selfissued** [comment]
I think we should add this information to the certification form - next to the date certified.  Then it's public but doesn't clutter the presentation at http://openid.net/certification/, which is already very busy and will become more-so when we add additional certification profiles for form post response mode, etc.

**Comment by zandbelt** [comment]
A split seems fine but I would argue that the profile and version are more important than the date at which one certified for a particular profile. Hence my proposal would be:
````
<implementation> <organization> <version> <a series of tick boxes for profiles>
````
Note I also swapped the "implementation" and "organization" columns.

**Comment by zandbelt** [comment]
@rohe Either you or me needs to add the version number the software so that is clear from the user facing webpages what version they're certifying against, and it should be clearly recorded in all server logs as well.

**Comment by rohe** [comment]
I can add it.

**Comment by zandbelt** [comment]
This was done in https://github.com/openid-certification/oidctest/commit/2245378d176e9171df3440f7de8ad5cca7b851f3 https://github.com/openid-certification/oidctest/commit/fb402fe294383c2b1f6fae712efb50142714ff27 https://github.com/openid-certification/oidctest/commit/0f484ceaa40484023ec42686b845d86d8fa386e4 and https://github.com/openid-certification/oidctest/commit/aa19a1d7d4c26db838b54c57340b56944be0ba0d

**Comment by zandbelt** [comment]
it is recorded in logs and displayed in the GUI since RP 1.0.0 and OP 2.0.0; the logs will be uploaded as part of the certification statement of a particular implementation/deployment
