### ISSUE TITLE
frontchannel tests missing notes

### ISSUE THREAD

**Issue by panva** [openid-certification/oidctest#160]
These tests are missing the Note about taking a screenshot and ignoring the test result.

- OP-FrontChannel-RpInitLogout-no-post_logout_redirect_uri
- OP-FrontChannel-RpInitLogout-only-state

**Comment by rohe** [comment]
Added notes

**Comment by panva** [comment]
OP-FrontChannel-RpInitLogout-no-post_logout_redirect_uri is still missing it, see #165
