### ISSUE TITLE
OP-FrontChannel-RpInitLogout-post_logout_redirect_uri-with-query

### ISSUE THREAD

**Issue by panva** [openid-certification/oidctest#164]
This test is missing, if both Front/Back channel mechanisms need to have tests replicated.

**Comment by rohe** [comment]
Added Front channel equivalent.

**Comment by panva** [comment]
We just deployed and this test didn't come up, did you commit it?

**Comment by rohe** [comment]
Sorry was to stressed. Checked it in but didn't push it. Done so now.

**Comment by zandbelt** [comment]
deployed now
