### ISSUE TITLE
OP-request_uri-Sig-any doesn't register request_uri if required to do so

### ISSUE THREAD

**Issue by marsangr** [openid-certification/oidctest#173]
At the moment the new test OP-request_uri-Sig-any [fails for me](https://op.certification.openid.net:60866/OP-request_uri-Sig-any) without recording any log (This is exactly the same situation I described back in #38.) For me it looks like this:

a) my OP announces require_request_uri_registration = "true", but still
b) the test tool doesn't register any request_uris, though later on
c) the test tool sends a request_uri during the auth request, to which logically
d) my OP answers "Invalid request: The client registration doesn't permit request_uri"

The other two tests OP-request_uri-Sig and OP-request_uri-Unsigned behave correctly.

**Comment by zandbelt** [comment]
@rohe can you confirm we need to change something here? If so, I'll take a look.

**Comment by rohe** [comment]
Sorry I've been too busy lately. I'll have a look at this beginning next week.

**Comment by rohe** [comment]
Which test instance is in use ? Have to look at the logs.
The functionality is there. Can't know why it's not used before I've seen the logs.

**Comment by marsangr** [comment]
https://op.certification.openid.net:60866/

**Comment by marsangr** [comment]
Can discuss this in person at Identiverse, if you are there...

**Comment by rohe** [comment]
That would have been nice if I'd been there but unfortunately not.
Hans is, I guess.

**Comment by rohe** [comment]
Hmm, I see others that have require_request_uri_registration = "true" and that gets request_uris in the client registration. So, what's different with you ? Haven't found that out yet.

**Comment by panva** [comment]
@marsangr i can see your provider does not echo the registered `request_uris` back to the RP, for mine it does and the test works.

That's the difference i could spot.

**Comment by panva** [comment]
👆 aand we have a winner, when i remove `request_uris` from the registration response the test tool does not use the one it sent with registration, e.g. `https://op.certification.openid.net:61784/requests/27027a68667f3020d2b092687090076861507fb774a7ba89454e8e1edb3646a4#jlO1BuMeKJS7bJMq` but uses another, i guess generic, one e.g. `https://op.certification.openid.net:61784/export/rZyPhjQ2Xw.jwt`

**Comment by panva** [comment]
@marsangr as a workaround for this (**optional** btw) test just make sure you echo back the recognized client metadata.

**Comment by rohe** [comment]
@panva is right, if the OP doesn't echo back the request_uris that is basically saying the OP doesn't accept that claim. One could argue that the RP should in that case not use another request_uri. Have to look at that.

**Comment by panva** [comment]
One could argue that if the op requires the registration of uris and doesn’t echo back the accepted uris the client should not continue. Or at the very least the suite should handle it and err

**Comment by rohe** [comment]
Agree

**Comment by marsangr** [comment]
Just contacted the vendor and made them aware about this issue.

**Comment by marsangr** [comment]
New version of the vendor software has fixed the issue. Sorry for the noise.
