### ISSUE TITLE
obsolete bitbucket repository

### ISSUE THREAD

**Issue by zandbelt** [openid-certification/oidctest#174]
Apparently there's an obsolete oidctest repository here:
https://bitbucket.org/openid/certification
we should remove it or provide a pointer/redirect to the Github repo in order to avoid confusion.

**Comment by rohe** [comment]
I don't think I can remove it.
Perhaps @selfissued can.

**Comment by selfissued** [comment]
I now remember what this was.  The OIDF asked Roland to snapshot his sources to bitbucket when we launched the certification program, so there was a second archival copy of them.

Given that Atlassian is going to delete this with other Mercurial repositories on June 1, 2020, per https://bitbucket.org/blog/sunsetting-mercurial-support-in-bitbucket, I'm not prone to put any time into having us delete it now.
