### ISSUE TITLE
new-op OP-Rotation-OP-Enc and OP-Rotation-OP-Sig show empty page 

### ISSUE THREAD

**Issue by selfissued** [openid-certification/oidctest#18]
From: Jaromir Talir [mailto:jaromir.talir@nic.cz]
Sent: Thursday, May 25, 2017 9:16 AM
To: Mike Jones <Michael.Jones@microsoft.com>
Cc: 'Roland Hedberg' <roland@catalogix.se>; Hans Zandbelt <hans.zandbelt@zmartzone.eu>
Subject: Re: Testing https://new-op.certification.openid.net:60000/

...

- OP-Rotation-OP-Enc and OP-Rotation-OP-Sig surprisingly show empty page when I continue test without doing any rotation.

**Comment by rohe** [comment]
Fixed in https://github.com/rohe/oidctest/commit/38a7f5c637ebac2463662b5905a265fee6d1e6e8

**Comment by selfissued** [comment]
When can we propagate this to new-op and let Jaromir know to re-test?

**Comment by zandbelt** [comment]
Confirmed by Jaromir,

> Testing https://new-op.certification.openid.net:60000/
> Jaromir Talir <jaromir.talir@nic.cz>	Wed, Jun 14, 2017 at 10:21 AM
> To: Hans Zandbelt <hans.zandbelt@zmartzone.eu>
> Cc: Certification <certification@oidf.org>
> Hi Hans,
> 
> both seems to me ok now.
> 
> Regards,
> Jaromir
> 
> On Tue, 2017-06-13 at 11:58 +0200, Hans Zandbelt wrote:
> > Hi Jaromir,
> >
> > Those issues [18][19] have been fixed at https://new-op.certification
> > .openid.net:60000 now.
> > Can you confirm that this works for you?
> >
> > Thanks,
> >
> > Hans.
> >
> > [18] https://github.com/openid-certification/oidctest/issues/18
> > [19] https://github.com/openid-certification/oidctest/issues/19
> >
