### ISSUE TITLE
RP logout test descriptions and group name correction

### ISSUE THREAD

**Issue by zandbelt** [openid-certification/oidctest#185]
[`rp-backchannel-rpinitlogout.json`](https://github.com/rohe/oidctest/blob/logout/test_tool/cp/test_rplib/rp/flows/rp-backchannel-rpinitlogout.json) belongs to group "RP Initiated BackChannel Logout"
whereas the others (e.g. [`rp-backchannel-rpinitlogout-lt-alg-none`](https://github.com/rohe/oidctest/blob/logout/test_tool/cp/test_rplib/rp/flows/rp-backchannel-rpinitlogout-lt-alg-none.json)) belong to group "RP Initiated Logout"

The [`example_conf.py`](https://github.com/rohe/oidctest/blob/logout/test_tool/cp/test_rplib/rp/example_conf.py) should also be extended with the new group name and [`config.py`](https://github.com/rohe/oidctest/blob/logout/test_tool/cp/test_rplib/rp/config.py) should be corrected to the right group name.

**Comment by rohe** [comment]
Fixed

**Comment by zandbelt** [comment]
that's rolled out on new-rp now; closing here

**Comment by zandbelt** [comment]
I am re-opening because it is not clear to me why there's a "RP Initiated BackChannel Logout" section but a bunch of tests named `rp-backchannel-*` are not appearing there but rather in the generic "RP Initiated Logout" section.

**Comment by rohe** [comment]
Removed the "RP Initiated Logout" group.
