### ISSUE TITLE
new-op OP-nonce-NoReq-noncode should provide intermediate screen like other "reject" tests 

### ISSUE THREAD

**Issue by selfissued** [openid-certification/oidctest#19]
From: Jaromir Talir [mailto:jaromir.talir@nic.cz]
Sent: Thursday, May 25, 2017 9:16 AM
To: Mike Jones <Michael.Jones@microsoft.com>
Cc: 'Roland Hedberg' <roland@catalogix.se>; Hans Zandbelt <hans.zandbelt@zmartzone.eu>
Subject: Re: Testing https://new-op.certification.openid.net:60000/

...

- test OP-nonce-NoReq-noncode should probably provide intermediate screen like other "reject" tests i.e. OP-redirect_uri-Missing. In this state it only displays error message on provider side but there is no way how to "mark" this test as completed.

**Comment by zandbelt** [comment]
This has been addressed in https://github.com/openid-certification/oidctest/commit/1dbdfb62dbde3303da91e906741b8a22bdcbf62f

**Comment by zandbelt** [comment]
Confirmed by Jaromir,

> Testing https://new-op.certification.openid.net:60000/
> Jaromir Talir <jaromir.talir@nic.cz>	Wed, Jun 14, 2017 at 10:21 AM
> To: Hans Zandbelt <hans.zandbelt@zmartzone.eu>
> Cc: Certification <certification@oidf.org>
> Hi Hans,
> 
> both seems to me ok now.
> 
> Regards,
> Jaromir
> 
> On Tue, 2017-06-13 at 11:58 +0200, Hans Zandbelt wrote:
> > Hi Jaromir,
> >
> > Those issues [18][19] have been fixed at https://new-op.certification
> > .openid.net:60000 now.
> > Can you confirm that this works for you?
> >
> > Thanks,
> >
> > Hans.
> >
> > [18] https://github.com/openid-certification/oidctest/issues/18
> > [19] https://github.com/openid-certification/oidctest/issues/19
> >
