### ISSUE TITLE
bring RP logout tests inline with OP logout tests wrt. requirement on id_token_hint

### ISSUE THREAD

**Issue by zandbelt** [openid-certification/oidctest#198]
`id_token_hint` should be present when `post_logout_redirect_uri` is present to expose the same behaviour as the OP tests

- https://bitbucket.org/openid/connect/issues/1032/rp-initiated-logout-proposal-for-client_id#comment-51373773
- https://bitbucket.org/openid/connect/issues/1071

**Comment by rohe** [comment]
Updated oidctest to do this.
It should eventually get into pyoidc but perhaps not before the draft has been changed.

**Comment by zandbelt** [comment]
that should be in the latest release then https://github.com/openid-certification/oidctest/releases/tag/v1.2.3, I will verify shortly
