### ISSUE TITLE
rp-backchannel-rpinitlogout: content type missing?

### ISSUE THREAD

**Issue by zandbelt** [openid-certification/oidctest#199]
According to https://openid.net/specs/openid-connect-backchannel-1_0.html#BCRequest the backchannel logout request should have the `Content-Type` set to `application/x-www-form-urlencoded`. It looks like the test suite (i.e. pyoidc) does not set this header, can you confirm?

**Comment by rohe** [comment]
You're right! Must change that in pyoidc. Will issue another PR when the one of post logout without a post_logout_redirect_uri has been handled unless I can combine them.

**Comment by rohe** [comment]
The RP has been accepted and merged into the master branch of pyOIDC.

**Comment by zandbelt** [comment]
in the latest release now https://github.com/openid-certification/oidctest/releases/tag/v1.2.3
