### ISSUE TITLE
OP-RpInitLogout-Discovery should not require check_session_iframe

### ISSUE THREAD

**Issue by selfissued** [openid-certification/oidctest#200]
The test OP-RpInitLogout-Discovery currently fails if check_session_iframe is not in the discovery metadata.  This test should only be looking for end_session_endpoint - which is part of RP-Initiated Logout, not check_session_iframe, which is part of Session Management. 

You can see this error at https://op.certification.openid.net:60046/test_info/OP-RpInitLogout-Discovery.

**Comment by rohe** [comment]
Have checked in a fix of oidctest.

**Comment by zandbelt** [comment]
it is in the latest release then https://github.com/openid-certification/oidctest/releases/tag/v1.2.3
