### ISSUE TITLE
OP log files: no extension, tar archive contains full path

### ISSUE THREAD

**Issue by zandbelt** [openid-certification/oidctest#22]
When downloading the tar archive with log files, two things seem to be off:
- the files contain the full path instead of the relative path
- the files have no extension (like .txt for the RP log files)

```
tar ztvf s_zmartzone.eu.id_token_token.IT.F.T.F.tar.gz 
-rw-r--r--  0 root   root     3154 Jun 13 10:42 usr/local/oidf/oidc_op/log/s_zmartzone.eu/id_token_token/IT.F.T.F/OP-Response-Missing
```

**Comment by selfissued** [comment]
Also, can we please skip the gzip step and just return the .tar file?  Releasing a .tar.gz file means that there are two steps that the tester has to take to get at his data.  We should just release .tar files like we do on the current OP certification site.  Thanks.

**Comment by rohe** [comment]
Fixed by
https://github.com/rohe/oidctest/commit/181430b260bf8f590b135fe3cdaa8c32716844b6 and
https://github.com/rohe/otest/commit/ee9e4fef1f18f2d77eb663ee6a8466e3de4eb42a

**Comment by zandbelt** [comment]
confirmed and rolled out on new-op
