### ISSUE TITLE
Wrong tests logs placement

### ISSUE THREAD

**Issue by Deivur** [openid-certification/oidctest#228]
Today figured out that test log could be placed in the wrong path.
As the documentation says https://openid.net/certification/rp_testing/ we expect to see logs here https://rp.certification.openid.net:8080/log/mod_auth_openidc. But now they duplicated in the one more place
https://rp.certification.openid.net:8080/log/log/mod_auth_openidc
Here are screenshots:
base folder
<img width="1437" alt="Screen Shot 2020-06-12 at 17 45 57" src="https://user-images.githubusercontent.com/8025638/84515207-d3856380-acd4-11ea-8f5b-e024dddfeb63.png">

nested folder
<img width="1440" alt="Screen Shot 2020-06-12 at 17 46 49" src="https://user-images.githubusercontent.com/8025638/84515227-da13db00-acd4-11ea-9afe-68f7a5a1ee75.png">

I have automated tests and they fail from time to time as can not retrieve log to verify state and they can't clean up logs after the end.
Is it an issue? Or it is expected and I need to handle such behavior?
Thanks, in advance!

**Comment by zandbelt** [comment]
That is unexpected indeed, it looks like at some point a bug was introduced in log placement; can you also test this against https://new-rp.certification.openid.net:8080? Also, you seem to indicate that this misplacement is intermittent, is it?

**Comment by Deivur** [comment]
@zandbelt thank you for the quick answer, I'll try today and get back to you with the result.

**Comment by zandbelt** [comment]
it seems that the server process got into a bad state: after a restart things seem to back to normal, please confirm

**Comment by Deivur** [comment]
With new endpoint https://new-rp.certification.openid.net:8080 looks everything good. Will this URL change in the future?
I ran tests locally with old endpoint https://rp.certification.openid.net:8080 and they passed as well.

**Comment by zandbelt** [comment]
please keep using  https://rp.certification.openid.net:8080 for now
