### ISSUE TITLE
Gather contact e-mails to notify testers of status changes

### ISSUE THREAD

**Issue by selfissued** [openid-certification/oidctest#24]
As we discussed on today's call, we need to notify those testers that we can about the change to new-op.  Can you please extract the e-mail addresses we have, Roland?  I realize that this won't be a complete list.

Also, can you please gather the WebFinger e-mail addresses from the RP testing info?  Many won't work, but we might as well try to contact the current RP testers too.  If that's the best info we have about them, let's use it, even though it will be flawed.  Thanks.

**Comment by zandbelt** [comment]
that info was not stored
