### ISSUE TITLE
at_hash has incorrect value rp-response_typeid_token+token

### ISSUE THREAD

**Issue by damienbod** [openid-certification/oidctest#27]
When I test using the public test server for id_token token, the at_hash value in the id_token does not match the at hash calculated from the access_token. 

TestData:

https://rp.certification.openid.net:8080/damienbod.id_token_token/rp-response_typeid_token+token

**access_token**
0ezwGz8LfaBpqjYineXUep6Aszx2GHplBoo%2BdaCzk1KLvMylFMe0SJ%2B7wgWg05GSU2CYeTJdsf%2Bo%2BhxRvJEadrrMveqyS7WvhDsqhtGFANUMl%2Fw%2Fvq4yEGmKsZx2uSvRVahFI3OtXEvRs5Jk%2B017IQ%3D%3D

**id_token**
eyJhbGciOiJSUzI1NiIsImtpZCI6ImFUMzNNc2tCdjF5b0poZU5Ia0xtVTBfa25WZjliS1lVVkVMSm9ITzZ1TjgifQ.eyJzdWIiOiAiMWIyZmM5MzQxYTE2YWU0ZTMwMDgyOTY1ZDUzN2FlNDdjMjFhMGYyN2ZkNDNlYWI3ODMzMGVkODE3NTFhZTZkYiIsICJhY3IiOiAiUEFTU1dPUkQiLCAiYXVkIjogWyJ6OUM5bFhNTTlOb3AiXSwgImF0X2hhc2giOiAiZDV1UU1GdE5LMjNRekJnREQ5UkFLQSIsICJub25jZSI6ICJOMC43MTk0ODkzNTE2OTYxMjQzMTQ5Nzg2NzkwODc3NCIsICJpc3MiOiAiaHR0cHM6Ly9ycC5jZXJ0aWZpY2F0aW9uLm9wZW5pZC5uZXQ6ODA4MC9kYW1pZW5ib2QuaWRfdG9rZW4tdG9rZW4vcnAtc2NvcGUtdXNlcmluZm8tY2xhaW1zIiwgImV4cCI6IDE0OTc5NTQzMDgsICJhdXRoX3RpbWUiOiAxNDk3ODY3OTA4LCAiaWF0IjogMTQ5Nzg2NzkwOH0.TX46J6AzZT2on7A2F2DOLc5-ERP5CiPh5TYR4sutclGJmEJggnD1J6CUJaaOT1uYtWfTn3hIehneBJsgwFNTcf7E7Hh94pt0l67IsahlnLuqSVxykKsocPpyiCgoieRlypNo9Xy0UbZKf_IHL7jW2xW7V0MMZ4p2GHAgX22yDg3aMZJ-XPV7VHopG_Afbrri47pLEvSfqhMyLZtgHEZAYaF1O66zFq1-9x06pDAb5lWlPMsTjewK5_RPSdDzXl0OPftCawGm4n_Cv8WZzmv5ZqcJH07aZkJHZkvrSA8twkkxoPsbwdwC_gi2D2eZAx8_egIFqgKYU0xUxzT9_JrF8Q

{
  "alg": "RS256",
  "kid": "aT33MskBv1yoJheNHkLmU0_knVf9bKYUVELJoHO6uN8"
}

"at_hash": "d5uQMFtNK23QzBgDD9RAKA",

---

access_token data hash : NAynNl-G8Gmg9OltA0f55A

**Comment by panva** [comment]
the access token value is actually

```
0ezwGz8LfaBpqjYineXUep6Aszx2GHplBoo+daCzk1KLvMylFMe0SJ+7wgWg05GSU2CYeTJdsf+o+hxRvJEadrrMveqyS7WvhDsqhtGFANUMl/w/vq4yEGmKsZx2uSvRVahFI3OtXEvRs5Jk+017IQ==
```

It seems you are trying to use its URI encoded for calculating the at_hash, this might also be the culprit in #28 

The at_hash value for the above token (using `xx256`) is `d5uQMFtNK23QzBgDD9RAKA` (correct one returned).

**Comment by damienbod** [comment]
thanks, will test this

**Comment by damienbod** [comment]
works, thanks for your help, must buy you a beer if I ever get the chance :)

**Comment by damienbod** [comment]
@panva Hi I tried this again, and it's not working for me.

https://rp.certification.openid.net:8080/damienbod.id_token_token/rp-response_type-id_token+token

**at_hash in the id_token**
9dxQAJJnJwJSjxpoEgDWvA

**access_token**
C71UYgoDSlBFFXyFRaW5Jps9ngl/rR2vofQNuyeLks3DE7NSn2LG9Qe+Dhaqw/5K6RE4t7bR7r53qrXi4DykJAJuL10icvcC7ujr6fACb42PlCQlo6j6aJJ5B3c6j1C3N/WB7OQs/r9eBUiqlE2yXw==

My at_hash: qYYQIZUvk04XKqNhSNVo1A

Don't see what's wrong. I feel fairly confident the client code works, tested it against 3 different OpenID servers with no problems, just this test server doesn't work.

Any ideas? Greetings Damien

**Comment by damienbod** [comment]
Here's another example with logs:

https://rp.certification.openid.net:8080/log/damienbod.id_token_token/rp-response_type-id_token+token.txt

From the server in the id_token:

qAWUlMNoufeaZ1E7b07_rg

My calculatation:

oURm1sO2tTlX0ZfcGM2CeLbhvpZYRTgATX7B29T6AyJJyRPJvpBpQe/XGQ4tewRIzVR1c/bbXsyxyi42XgNuCrPH+k4DRdDXI566EFwXU6N5j5anQnGYQvmC3g4Dzxfua6vH+PnXisyzjEIdu7CzgQ==

dvKu3k3rl2KuIlFGRTQ5Lw

**Comment by panva** [comment]
Hi @damienbod, your calculations are incorrect.

```
at = "C71UYgoDSlBFFXyFRaW5Jps9ngl/rR2vofQNuyeLks3DE7NSn2LG9Qe+Dhaqw/5K6RE4t7bR7r53qrXi4DykJAJuL10icvcC7ujr6fACb42PlCQlo6j6aJJ5B3c6j1C3N/WB7OQs/r9eBUiqlE2yXw=="
at_hash = "9dxQAJJnJwJSjxpoEgDWvA"
```

```
at = "oURm1sO2tTlX0ZfcGM2CeLbhvpZYRTgATX7B29T6AyJJyRPJvpBpQe/XGQ4tewRIzVR1c/bbXsyxyi42XgNuCrPH+k4DRdDXI566EFwXU6N5j5anQnGYQvmC3g4Dzxfua6vH+PnXisyzjEIdu7CzgQ=="
at_hash = "qAWUlMNoufeaZ1E7b07_rg"
```

Not sure what the `hextob64u` does, but you might wanna take a look at https://www.npmjs.com/package/oidc-token-hash and how it's calculated there, i remember having issues connected to encoding, the moment i stopped encoding/decoding and just used buffers it clicked. I'm fairly sure you can include `oidc-token-hash` in your angular code using webpack or similar.

**Comment by panva** [comment]
For reference, from the Core 1.0 spec,

- token `jHkWEdUXMU1BwAsC4vtUsZwnNvTIxEl0z9K3vx5KF0Y` should produce hash `77QmUPtjPfzWtF2AnpK9RQ`
- token `Qcb0Orv1zh30vL1MPRsbm-diHiMwcLyZvn1arpZv-Jxf_11jnpEX3Tgfvk` should produce hash `LDktKdoQak3Pk0cnXxCltA`

**Comment by damienbod** [comment]
@panva excellent, thanks
