### ISSUE TITLE
rp-id_token-kid-absent-single-jwks result

### ISSUE THREAD

**Issue by damienbod** [openid-certification/oidctest#29]
https://rp.certification.openid.net:8080/damienbod.id_token_token/rp-id_token-kid-absent-single-jwks/registration

https://rp.certification.openid.net:8080/log/damienbod.id_token_token/rp-id_token-kid-absent-single-jwks.txt

I reject this because I have 4 items with kid ids in the https://rp.certification.openid.net:8080/static/jwks_5hZ6PW0uKOqzGcMK.json

Test states:
Accepts ID Token without 'kid' claim in JOSE header if only one JWK supplied in 'jwks_uri'

Have I misunderstood something here, or is the test incorrect?

Greetings Damien

**Comment by panva** [comment]
Hello @damienbod, the point is, out of the four listed only ONE can be used for `RS256` id token signature validation, so a `kid` is not necessary in this case and the RP should be able to select the right one to validate with.

@zandbelt, maybe we should change the `Info` for this test to 

```
Use the single matching key out of the Issuer's published set to verify the ID Tokens signature and accept the ID Token after doing ID Token validation.
```

**Comment by damienbod** [comment]
@panva Thanks
