### ISSUE TITLE
missing iss and aud claims in signed Request Objects

### ISSUE THREAD

**Issue by panva** [openid-certification/oidctest#34]
every OP test that includes sending a request object (either by reference or value) should have two extra claims in the request object it sends (or references by sending request_uri)

- `iss` with the value being the client id
- and `aud` being the OP's issuer identifier

From Core 1.0
> If signed, the Request Object SHOULD contain the Claims iss (issuer) and aud (audience) as members. The iss value SHOULD be the Client ID of the RP, unless it was signed by a different party than the RP. The aud value SHOULD be or include the OP's Issuer Identifier URL.

Now i added these SHOULD validations to my OP and tests don't pass anymore. If the OP tool were including them both OPs with and without this validation would be passing.

**Comment by panva** [comment]
The tests also do not show any logs if the requests get rejected because of this validation is in place. You can see the behavior on https://new-op.certification.openid.net:60011/#request

**Comment by rohe** [comment]
Now, what is a SHOULD validation ?
SHOULD is NOT the same as MUST.
So, if your OP rejects requests because iss and/or aud is missing then I think it's not following the spec.

**Comment by panva** [comment]
Would you say these should be validated when present, but not validated when omitted by the client?

**Comment by panva** [comment]
I think i get it now, thank you @rohe, understand things a bit more once again ;)

**Comment by rohe** [comment]
One is never done learning :-)
