### ISSUE TITLE
port assignment for new registrations fails

### ISSUE THREAD

**Issue by zandbelt** [openid-certification/oidctest#35]
There seems to be a problem with the port assignment of new registrations:

> Now about the tool: I think we are having some (concurrency?) issues in
> the new version! I just registered a new test instance. This was the
> success message:
> 
> Your test instance "https://auth.freedom-id.de:basic-autoreg" has been
> start as https://op.certification.openid.net:60001
> 
> However, that port is bringing me to the test instance of another issuer
> which is not mine (idam.metrosystems.net). Could you please double check
> what is going on?

I guess it is always going to take 60001 for new registrations?

(PS: I've manually fixed this for the tester using port 61011)

**Comment by rohe** [comment]
Wonder what's so special with 60219 and 60220 ??

**Comment by zandbelt** [comment]
I do think I've found the correlation: it seems that the entries listed above have one thing in common: they have 2 entries, one with their "plain" name, and one with their "urlencoded" name. The first one has the new port. I guess 60219 was the first free port after the migration.

So it may just be a matter of finding where the url-encoding goes wrong, fix that and remove the entries with the "plain" keys.

Not sure if the issue is with the migration script or the current code.

**Comment by zandbelt** [comment]
It looks like *unquoting* is done very specifically here:
https://github.com/openid-certification/oidctest/blob/master/src/oidctest/ass_port.py#L19
so I guess the migration script should have created plain keys rather than url-encoded ones?
(I must admit that I'm confused since the `assigned_ports.json.backup` file *does* have url-encoded keys...)

**Comment by zandbelt** [comment]
I think I've got it: the migration script must have been off and even the backup files were wrong because they were created out of earlier migrations that were also using urlencoded keys. I don't think we noticed that before because no-one was using such an issuer/tag combo (yet) on new-op.

Additionally I found a bug in displaying URL-unsafe tag names in the list of tags for an entity; that is fixed in 9ca443e

So I think we need to do the migration again, taking into account any new registrations that have been done in the mean time:
```
hzandbelt@new-op:/usr/local/oidf/oidc_op$ cat conf_srv.log | grep "/action/create" | grep -v zmartzone | cut -d"?" -f2 | cut -d"&" -f1 | sort | uniq

iss=
iss=Gmail.well-known
iss=http%3A%2F%2F31.18.108.162%3A8080%2F
iss=http%3A%2F%2F95.91.228.235%3A8080%2F
iss=http%3A%2F%2Fhref.synology.me%3A8080%2F
iss=https%3A%2F%2F172.17.0.1%3A9443%2Fcarbon%2F
iss=https%3A%2F%2Faccounts.google.com
iss=https%3A%2F%2Fapi.developer.vodafone.com
iss=https%3A%2F%2Fauth.freedom-id.de
iss=https%3A%2F%2Fkrmidentity.azurewebsites.net
iss=https%3A%2F%2Flocalhost%3A9443%2Fcarbon%2F
iss=https%3A%2F%2Fpeterahl.auth0.com%2F
iss=https%3A%2F%2Fsso.nguyenkim.com
iss=https%3A%2F%2Ftest.veb.audi-connect.de%2F
iss=https%3A%2F%2Fti-test.bbas.no%2Foidc%2F
iss=sara.pixelite.nl
```

**Comment by rohe** [comment]
OK, I can fix this but I need some time and as I said in an earlier mail I don’t have any
continuous time (more then an hour) before Thursday afternoon when I’m back home again.

Now, I don’t think this is a major problem since the number of testers that will encounter a problem
between now and then is probably not more then a handfull at the most.

If you think otherwise tell me so.

**Comment by zandbelt** [comment]
All done now with the new migration tools; deployed in RP 1.0.3 and OP 1.0.5:
https://github.com/openid-certification/oidctest/releases/tag/v1.0.5
