### ISSUE TITLE
docker-compose up not working on windows machine

### ISSUE THREAD

**Issue by deanraspa** [openid-certification/oidctest#37]
When trying to run the docker-compose up command referred to in the readme, none of the containers were starting.  
After a little digging, I noticed that the issue was due to the fact that git for windows changes the line endings on all of the *.sh and *.py files to the windows standard CRLF instead of the expected LF only.   I was able to get around the issue by adding a .gitattributes file to the root directory with the following contents:
```
*           text=auto
*.sh        text eol=lf
*.py        text eol=lf
```
I do not see any contribution guidelines anywhere, so was unsure how to submit a pull request with the new file to resolve this issue for others in a similar situation.

**Comment by zandbelt** [comment]
That is solved now in the master and stable-release-1.0.x branches. Thanks for the report and the proposed fix.
