### ISSUE TITLE
Warnings in OP-scope-* tests for not supported scopes

### ISSUE THREAD

**Issue by marsangr** [openid-certification/oidctest#39]
My server at
https://auth.freedom-id.de/.well-known/openid-configuration

clearly states that the only scope supported is "openid". However, the scope test cases, take OP-Scope-All for instance (https://op.certification.openid.net:60381/test_info/OP-scope-All), complain with the following warning

WARNING
Warnings:
No support for: scopes_supported=['profile', 'email', 'address',
'phone']

My server processes the request without returning an error and doesn't return the claim, which should be OK. So I believe the test result should still be "Passed" without any warnings.

**Comment by selfissued** [comment]
You can pass certification with warnings.  That said, it's expected that conforming OpenID Connect implementations will support all the standard scopes.  So I believe that the tests are doing the right thing.

**Comment by marsangr** [comment]
OpenID Connect core spec clearly states that the only mandatory scope is "openid" and the rest are optional, so I think that the warnings are unfair. That said, I can live with this behavior.
