### ISSUE TITLE
Types for claims returned not being checked

### ISSUE THREAD

**Issue by selfissued** [openid-certification/oidctest#40]
We are not flagging it when claims are returned with the wrong JSON types.  For instance, the Mvine results returned "middle_name": null - which isn't a string as required and "updated_at": "20170328081544Z" - when a number is required.  These results currently are PASSED whereas they should be FAILED.

We should also be issuing WARNINGs when empty strings are returned as claim values - such as "middle_name": "".

**Comment by rohe** [comment]
This needs an update to pyoidc. I have issued a Pull Request with the necessary enhancements.

**Comment by zandbelt** [comment]
This was addressed in pyoidc here:
https://github.com/OpenIDC/pyoidc/pull/401
and here:
https://github.com/OpenIDC/pyoidc/pull/418
and is part of pyoidc version >=  0.11.0

**Comment by zandbelt** [comment]
as it appears that would pyoidc > 0.11.0.1

**Comment by zandbelt** [comment]
pyoidc 0.12.0 is now deployed as part of OP release 2.0.7
