### ISSUE TITLE
More flexibility for the OP-Req-login_hint test

### ISSUE THREAD

**Issue by marsangr** [openid-certification/oidctest#41]
The test requires the profile configuration parameter "login_hint". It then creates the string
$login_hint + "@" + $issuer
and sends that as the value of the auth request parameter login_hint.

First, that's a bit confusing, but second -and more important- it's too rigid: for instance my Auth-Endpoint does not expect that @$issuer notation and thus doesn't recognize the user.

My enhancement request is to pass the profile configuration parameter "as is" in the auth request login_hint. That allows for all possible options.

**Comment by panva** [comment]
If you navigate back to https://op.certification.openid.net:60000 and find your instance, clicking on reconfigure there's a login_hint field you can provide. That login_hint should then be used.

**Comment by marsangr** [comment]
Thanks, I do know that. The problem is that whatever the value I write in the configuration field, the test case always will add "@issuer" afterwards when sending the login_hint request parameter.

**Comment by panva** [comment]
I cannot confirm this behavior you are describing, ran my test only few minutes ago.

**Comment by zandbelt** [comment]
I believe the test tool adds `@<issuer>` indeed unless a suffix is already provided. We could change that to accept "non-scoped" identifiers as well.

**Comment by selfissued** [comment]
We can just use the login hint value as-is.

**Comment by marsangr** [comment]
Works like a charm. Thanks!
