### ISSUE TITLE
.tar files have truncated names and are gzipped

### ISSUE THREAD

**Issue by selfissued** [openid-certification/oidctest#43]
If you download the tar file from https://rp.certification.openid.net:8080/log/mod_auth_openidc, you'll get a file of the name "of_auth_openidc.tar.gz".  Note that the "m" in "mod" was truncated.

Also, we agreed not to gzip the tar files, since some machines won't have gzip on them.

**Comment by zandbelt** [comment]
I'm reserving the "bug" label for issues that yield incorrect results wrt. the conformance and as such have highest priority.
