### ISSUE TITLE
Robustness of test OP-UserInfo-Enc

### ISSUE THREAD

**Issue by marsangr** [openid-certification/oidctest#46]
In one of the "extra" tests
https://op.certification.openid.net:60381/test_info/OP-UserInfo-Enc
the test suite aborts for incomprehensible reasons

12.846 fault 'NoneType' object is not subscriptable

(as a matter of fact, I know I shouldn't pass the test, because my
userinfo-endpoint is still delivering a non-encrypted
answer, but I would expect the test to be "red" and not to abort)

**Comment by rohe** [comment]
OK, I know what the fault is. 
Applying a fix.

**Comment by zandbelt** [comment]
I believe this was addressed in https://github.com/rohe/oidctest/commit/8fa9fa0cd805d2c136a35f8251c63b20f57c62df and will be rolled out as part of OP 2.0.7

**Comment by zandbelt** [comment]
OP release 2.0.7 is now deployed

**Comment by marsangr** [comment]
Sorry, this issue is again/still there, please cf
https://op.certification.openid.net:60381/test_info/OP-UserInfo-Enc
