### ISSUE TITLE
Bug in test OP-Rotation-RP-Sig

### ISSUE THREAD

**Issue by marsangr** [openid-certification/oidctest#50]
From our point of view it is impossible to pass the test if the client registration parameters are honored:

At client registration time the client declares itself to restrict itself to

    "grant_types": [
        "authorization_code"
    ]

but later on, it attempts a grant_type "refresh_token". No wonder we don't pass the test

status_code:400 message:{"error_description":"The client is not authorized to use this grant type","error":"unauthorized_client"}

**Comment by marsangr** [comment]
Any chances the test might be fixed? We are aiming at a certification.

**Comment by rohe** [comment]
Sorry, been on vacation.
I'll fix this tomorrow.
Will get into the official test site when Hans is happy with the change.

**Comment by selfissued** [comment]
Roland wrote "Fixed with a configuration change".  The fix needs to be verified.

**Comment by zandbelt** [comment]
This was addressed in:
https://github.com/rohe/oidctest/commit/104375d8a78dca5ae8dc59c8c505e0e72a3b2dee
and will be rolled out with OP 2.0.7

**Comment by zandbelt** [comment]
OP release 2.0.7 is now deployed
