### ISSUE TITLE
Connection refused by '/token' endpoint

### ISSUE THREAD

**Issue by estroz** [openid-certification/oidctest#52]
I am unable to successfully hit my OP's `/token` endpoint. All test cases that do so show the following exception (`127.0.0.1:5556/dex` is the OP's local issuer):
```
ConnectionError:HTTPConnectionPool(host='127.0.0.1', port=5556): Max retries exceeded
with url: /dex/token (Caused by NewConnectionError(': Failed to establish a new
connection: [Errno 111] Connection refused',))
```
I have tried using both a provided test instance (see [the logs](https://op.certification.openid.net:60232/log/s_accounts.google.com/first/C.F.F.F)) and a local instance deployed following instructions in the README, and see the same errors in both cases. The `/auth` endpoint works, and I have successfully `curl`'d the `/token` endpoint with data from test cases and received appropriate responses, so the issue is not with the OP itself. Has anyone seen a similar issue, or have any idea what could be causing failed connections?

**Comment by estroz** [comment]
Issue unrelated to tests

**Comment by kakarlus** [comment]
i have the same problem running the oidc conformance tests in local, how did you solve this?
