### ISSUE TITLE
INSTALL.md appears to be outdated

### ISSUE THREAD

**Issue by vpavic** [openid-certification/oidctest#57]
[INSTALL.md](https://github.com/openid-certification/oidctest/blob/master/INSTALL.md) contains instructions to clone the https://github.com/rohe/oidctest.git repo, instead of this repo.

On a side note, the project contains are a few more references to the upstream repo, see https://github.com/openid-certification/oidctest/search?utf8=%E2%9C%93&q=%22rohe%2Foidctest%22&type=.

**Comment by zandbelt** [comment]
Agree; I believe the `INSTALL.md` itself can now be removed since it is superseded by `README.md` and the Docker instructions that show step-by-step how to produce a running setup.
