### ISSUE TITLE
Help needed on implicit/hybrid flows

### ISSUE THREAD

**Issue by KimRasmussen** [openid-certification/oidctest#58]
Hi,

I am sure I am missing something simple, but if I go to https://op.certification.openid.net:60961/ and click on e.g. "OP-Response-id_token+token" - then I authenticate, and redirect back to https://op.certification.openid.net:60956/authz_cb with the various tokens as url fragment parameters. I can see that it downloads a very small piece of javascript code that simply picks up the fragment and posts it to https://op.certification.openid.net:60956/authz_post - but this seems to just display the "front page" listing the tests without updating the test or creating a trace I can see.

Could you point me in the right direction ?

Thanks again for all your help.
/Kim

**Comment by zandbelt** [comment]
From what I can see the `at_hash` cannot be validated:
```
oic.oic.message.AtHashError: Failed to verify access_token hash
```
You may be interested in: 
https://bitbucket.org/openid/connect/issues/1005/clarify-left-truncated-sha-2-hash-in

**Comment by KimRasmussen** [comment]
Thanks for the pointer, providing the correct hash fixed it.

Thanks again.
