### ISSUE TITLE
Tests send unnecessary client_id parameter when using basic Auth

### ISSUE THREAD

**Issue by TomDemeranville** [openid-certification/oidctest#61]
The new test suite includes a redundant client_id parameter when using basic auth to access the token endpoint.  This confuses some implementations.  Please return to previous behaviour.

**Comment by zandbelt** [comment]
I would like to point out that the OAuth 2.0 spec says near the end in: https://tools.ietf.org/html/rfc6749#section-3.2

> The authorization server MUST ignore unrecognized request parameters. 

Thus I would argue that when the basic authentication test is executed, the OP should perform basic authentication and any irrelevant parameters to the token endpoint should be ignored.

But we'll need to discuss this in the certification team and followup with a commonly shared view on this.

**Comment by TomDemeranville** [comment]
I'd say that that the problem here is not about unrecognised parameters.  

It can be seen as the client trying to provide credentials in two different ways, which makes for ambiguity, and in our case, failure.  The client_id parameter IS recognised, but the matching parameter for the client secret is missing.

**Comment by zandbelt** [comment]
@rohe can you take a look?

It seems it is added as part of pyoidc, but it also seems that is is done so for the last year or so:
https://github.com/OpenIDC/pyoidc/blob/master/src/oic/oauth2/__init__.py#L387

**Comment by selfissued** [comment]
I agree that the client_id should not be sent in two different locations, as it can confuse implementations.

**Comment by rohe** [comment]
Will have a look.

**Comment by zandbelt** [comment]
I produced a fix https://github.com/zmartzone/pyoidc/commit/2f1aeaff17410ec75f77956b58c485c591eb223c  but I am worried about why in the original code it was explicitly always included which seems the exact opposite...

**Comment by zandbelt** [comment]
a pyoidc snapshot from the master branch that contains this fix is now rolled out on the production and test environments; you'll need to restart your instance if you want to use this (and make sure it now references 2.0.12)
