### ISSUE TITLE
Encounter Internal Server Error in "Support request_uri request parameter" test

### ISSUE THREAD

**Issue by wreulicke** [openid-certification/oidctest#64]
I am trying Basic profile tests with dynamic discovery configurations.

if "Support request_uri request parameter" test run, test suites return error indicating Internal Server Error occurred.
But the error message has "request_uri parameter not supported".

This tests is ignorable?
My discovery endpoint provides wrong information?
Or, test suites has bug?

**Comment by zandbelt** [comment]
Your Discovery metadata document at https://barista.classmethod.info/.well-known/openid-configuration specifies:
```
  "request_uri_parameter_supported": false,
```
which indicates that consuming the `request_uri` parameter (and thus this test) is not supported and is why the test suite does not proceed. See:
http://openid.net/specs/openid-connect-discovery-1_0.html#ProviderMetadata

**Comment by zandbelt** [comment]
Assuming this addressed your question I'm closing this.
