### ISSUE TITLE
OP-Rotation-RP-Sig dynamic registration grant_types missing implicit for hybrid modes

### ISSUE THREAD

**Issue by panva** [openid-certification/oidctest#68]
When running `OP-Rotation-RP-Sig` under any of the hybrid response types (`CT, CIT, CI`) the dynamic client registration `grant_types` property is missing the `"implicit"` value.

**Comment by panva** [comment]
```json
{
    "application_type": "web",
    "contacts": [
        "roland@example.com"
    ],
    "grant_types": [
        "authorization_code",
        "refresh_token"
    ],
    "jwks_uri": "https://op.certification.openid.net:61082/static/jwks_61082.json",
    "post_logout_redirect_uris": [
        "https://op.certification.openid.net:61082/logout"
    ],
    "redirect_uris": [
        "https://op.certification.openid.net:61082/authz_cb"
    ],
    "request_uris": [
        "https://op.certification.openid.net:61082/requests/8c6576355085b78befea72b4fb2e63a2c02d10be9d0fd370b4d8fb727c62cc42#dZD3HkbCHYY8lxUY"
    ],
    "response_types": [
        "code token"
    ],
    "token_endpoint_auth_method": "private_key_jwt"
}
```

**Comment by zandbelt** [comment]
Adding it statically to the JSON description of the test `OP-Rotation-RP-Sig.json` is easiest only if we agree that it doesn't hurt backwards compatibility: e.g. for the "C" return_type the suite would now also register "implicit" as additional grant_type. If that's not desired we'll need to think of a more complex solution in code.

**Comment by panva** [comment]
some servers might actually require `response_types` to contain at least one implicit/hybrid member type when they encounter `implicit` in the grant_types

**Comment by zandbelt** [comment]
yeah; one could argue that's not in scope of the spec thus certification but it does complicate matters since it is not incorrect either

**Comment by panva** [comment]
http://openid.net/specs/openid-connect-registration-1_0.html#ClientMetadata shows implicit as only part of implicit and hybrid response types

**Comment by zandbelt** [comment]
isn't that defining the MUST relationship the other way around?

**Comment by panva** [comment]
I believe you are right, on the other hand, if there's no implicit response type registered, why declare that the client will use it. I'm okay with pushing the implicit value in statically so long as we keep an eye out for a clean solution should some providers complain.

**Comment by selfissued** [comment]
@panva points out that the supported grant types should align with the supported response types.  Let's discuss this together when we also have @rohe on a call.

**Comment by selfissued** [comment]
Per the call discussion today, we should populate the grant types supported based on the response type.

**Comment by zandbelt** [comment]
https://github.com/OpenIDC/pyoidc/commit/23efe6dd0638c23e0db90e11d86634c560a92c55

**Comment by zandbelt** [comment]
The "populate grant types supported based on the response type" feature is now rolled out on production as part of [OP release 2.0.14](https://github.com/openid-certification/oidctest/releases/tag/v1.0.17). @panva  please confirm.

**Comment by panva** [comment]
👍
