### ISSUE TITLE
null *_alg dynamic registration properties

### ISSUE THREAD

**Issue by zandbelt** [openid-certification/oidctest#69]
follows after #67 

> I looked into why my server implementation was ignoring null values in the first place, the reason is the supported RFC7592 which mentions servers MAY ignore null and empty string values. This is mentioned for the update request only and is not mentioned in OIDC Dynamic Client Registration 1.0 at all.
> 
> After fixing my provider implementation (not having it ignore null values for create) i found the same affects OP-request-Unsigned aswell.
> 
> request_object_signing_alg=null is also sent for OP-request_uri-Enc, however here i would say that either a specific alg is chosen or the property is not sent at all (is omitted) to have the * behaviors of OPs kick in.
> 
> userinfo_signed_response_alg=null is also sent for OP-UserInfo-Enc and OP-Rotation-RP-Enc where the value should either not be sent or a supported one should be chosen.
> 
> request_object_signing_alg
> OPTIONAL. JWS [JWS] alg algorithm [JWA] that MUST be used for signing Request Objects sent to the OP. All Request Objects from this Client MUST be rejected, if not signed with this algorithm. Request Objects are described in Section 6.1 of OpenID Connect Core 1.0 [OpenID.Core]. This algorithm MUST be used both when the Request Object is passed by value (using the request parameter) and when it is passed by reference (using the request_uri parameter). Servers SHOULD support RS256. The value none MAY be used. The default, if omitted, is that any algorithm supported by the OP and the RP MAY be used.
> test instance set to run against this OP https://op.certification.openid.net:60409

**Comment by panva** [comment]
The relevant logs
- https://op.certification.openid.net:60409/test_info/OP-request-Unsigned
- https://op.certification.openid.net:60409/test_info/OP-request_uri-Enc
- https://op.certification.openid.net:60409/test_info/OP-UserInfo-Enc
- https://op.certification.openid.net:60409/test_info/OP-Rotation-RP-Enc

**Comment by panva** [comment]
my recommendations:

- for OP-request-Unsigned set request_object_signing_alg to "none" (as in #67)
- for OP-request_uri-Enc remove request_object_signing_alg from the registration request
- for OP-UserInfo-Enc and OP-Rotation-RP-Enc remove userinfo_signed_response_alg from the registration request

removing the properties should result in the same OP behaviors, only it won't be sending an invalid (null) value and fail reg request for the ones that have stricter validations

**Comment by zandbelt** [comment]
that's now merged and deployed to `new-op`; it will be included in the next release to production

**Comment by zandbelt** [comment]
part of released 2.0.11
