### ISSUE TITLE
Authorization Code Reuse Test Partial Result

### ISSUE THREAD

**Issue by sjudson** [openid-certification/oidctest#7]
When running the authorization code reuse tests (both the immediate and thirty-second delay tests) a `PARTIAL RESULT` message (with associated question mark on status bubble) is shown, despite a conformant 403 Access Denied response with error `invalid_grant`, as is consistent with the OAuth 2.0 specification. [[RFC 6749]](https://tools.ietf.org/html/rfc6749#section-5.2)

```
 invalid_grant
               The provided authorization grant (e.g., authorization
               code, resource owner credentials) or refresh token is
               invalid, expired, revoked, does not match the redirection
               URI used in the authorization request, or was issued to
               another client.
```

These tests return green in the old testing environment, as I would expect.

Old:

![code_authcode_reuse_good](https://cloud.githubusercontent.com/assets/20324824/25407452/56ef7b6c-29d8-11e7-81e5-5a46eb88807d.jpeg)

New:

![code_authcode_reuse](https://cloud.githubusercontent.com/assets/20324824/25407460/5b8e3c44-29d8-11e7-8d92-78c3287a8f88.jpeg)

**Comment by rohe** [comment]
The problem is that you're returning a 403.
If RFC 6749 says anything about HTTP error codes it is that it should be a 400.
For some reason OIDC core has added 401 just for Userinfo responses.
No one mentions 403. 
I have OPs returning a 200 with an error message you're the first returning a 403 :-)
I can make the tool also accept 403 but it will take a while.

**Comment by selfissued** [comment]
We should issue a warning if the status code is not the expected one.

**Comment by selfissued** [comment]
A warning should be issued if it's not a 401 (or possibly a 400).  The use of 403 is wrong, and should result in a warning.

**Comment by arekkas** [comment]
This took me some while to figure out, it would be great if the test tool showed a warning or potentially fail if 403 was issued.

**Comment by zandbelt** [comment]
this is rolled out now on production (and test) as part of release 2.2.0

**Comment by zandbelt** [comment]
that's rolled out now on production (and test) as part of release 2.2.0
