### ISSUE TITLE
id_token_signing_alg_values not checked

### ISSUE THREAD

**Issue by andyroid83** [openid-certification/oidctest#71]
At the metadata endpoint

> id_token_signing_alg_values_supported
> REQUIRED. JSON array containing a list of the JWS signing algorithms (alg values) supported by the OP for the ID Token to encode the Claims in a JWT [JWT]. The algorithm RS256 MUST be included.

Mistakenly we had S256 rather than RS256 in there. As this is considered a MUST I had expected the test suite to pick that up. Maybe a check to be added?

Thanks for a great tool!

(BTW, maybe a pointer at https://github.com/rohe/oidctest to this repo would be good if this is where issues should be filed?)

**Comment by zandbelt** [comment]
I agree we could add such an additional "assert" element to the `OP-Discovery-Config` test.

**Comment by selfissued** [comment]
We should add a check that RS256 is present.

**Comment by zandbelt** [comment]
part of released 2.0.11
