### ISSUE TITLE
Config of client's private signing key for OP test

### ISSUE THREAD

**Issue by travisspencer** [openid-certification/oidctest#73]
When the test tool runs `OP-ClientAuth-SecretJWT`, it uses a private key to sign a JWT that it sends in the `Authorization` header as a bearer token. For the OP under test to verify this, it has to have the corresponding public key. In the client-related settings of the tool, there is a way to configure the JWKS, JWKS URI, and many other settings. However, there is no way to set the private key. Consequently, there is no way to automate this test. 

ATM, we are having to update the Docker container with a key when it spins up. It would be nice if there was a setting where we could provide the private key somehow. If so, then the OP could also be configured, and the test could be automated.

**Comment by travisspencer** [comment]
The approach of setting the key as the container seems to have failed even :-( The test creates a new key as it starts. Any guidance or tips or hidden features that could help here?

**Comment by zandbelt** [comment]
Yeah, I believe there's no static / pre-provisioned key so restarts of the container would generate a new one. @rohe: not sure if there's a way around that?

**Comment by zandbelt** [comment]
@travisspencer when the Client registeres with your OP it should send a `jwks_uri` as part of the registration request. On that URI the (public part of) the JWK used to sign the JWT for client authentication is published. That should be sufficient for your OP to validate the JWT.

**Comment by travisspencer** [comment]
That should be sufficient, @zandbelt . We've managed to monkey patched the Docker container for now, but will move over to that in time. Thanks for the help and support. Closing this ticket.
