### ISSUE TITLE
Enable use of endpoints containing query parameters

### ISSUE THREAD

**Issue by selfissued** [openid-certification/oidctest#74]
I created an OP test configuration that tries to use Microsoft's test IdP deployment, rather the production deployment.  The way the test slice is selected at runtime is to add the query parameter `?slice=testslice` to the endpoints.  So for instance, the authorization endpoint value in this configuration is `https://login.microsoftonline.com/66522826-e2e1-4cd9-82f5-6222397816bb/oauth2/v2.0/authorize?slice=testslice`.

Unfortunately, when the test code tries to use this endpoint, it adds a second quotation mark and the authentication parameters to this URL, rather than prefixing the parameters with an ampersand.  This results in illegal authentication request URLs with two question marks in them like this one `https://login.microsoftonline.com/66522826-e2e1-4cd9-82f5-6222397816bb/oauth2/v2.0/authorize?slice=testslice?client_id=8be0e753-bc24-40bb-ba3d-ef2335d949cd&redirect_uri=https%3A%2F%2Fop.certification.openid.net%3A61067%2Fauthz_cb&scope=openid&response_type=code&nonce=r1rV0uhhMPwaPDsq&state=wBMoRGQWcn7hc8sP`.

You can test this using the configuration at `https://op.certification.openid.net:61067/`, which uses the issuer `https://login.microsoftonline.com/66522826-e2e1-4cd9-82f5-6222397816bb/v2.0`.

Can you please add a check in the URL construction code so that `&` is used rather than `?` when the URL being added to already contains a `?`?  That would a huge help!

**Comment by rohe** [comment]
I've issued a PR on pyoidc where the problem resides (https://github.com/OpenIDC/pyoidc/pull/469).
It will hopefully be accepted shortly.

**Comment by zandbelt** [comment]
that's merged into pyoidc master branch now and rolled out on `new-op`; it should be in the next release to production, either through a released version of pyoidc or through a checkout of a specific commit of the master branch on production

**Comment by selfissued** [comment]
The deployment on new-op worked correctly.  You can kick the tires at https://new-op.certification.openid.net:60009/ if you like.  Please deploy this fix to production.

**Comment by zandbelt** [comment]
part of released 2.0.11
