### ISSUE TITLE
OP Configuration UI should have help for all fields

### ISSUE THREAD

**Issue by selfissued** [openid-certification/oidctest#75]
Trying to create a manual configuration, I ran across several fields that I didn't know the correct syntax for.  For instance, I don't know which of these is the right syntax for the response_types_supported field:
	`"code", "id_token"`
or
	`["code", "id_token"]`
and I don't know if this is accepted or not:
	`code`

We should add help text for all the input fields, preferably with a clickable question mark icon that pops up a help window describing the syntax and giving an example or two.

**Comment by zandbelt** [comment]
I deployed an experimental feature/solution for "tooltips" on the test environment: https://new-op.certification.openid.net:60000

Please review by creating a new instance at https://new-op.certification.openid.net:60000/new (preferably selecting "Dynamic Provider Information Discovery" before clicking "Create") and then hover over the `Info` buttons on the far right in the configuration screen.

Unfortunately font markup is not possible in this type of tooltips.

**Comment by selfissued** [comment]
This is really useful, Hans!  Please proceed to finish this and deploy it to production.

**Comment by zandbelt** [comment]
the inital batch of .help texts is deployed to production now; coverage must still be completed

**Comment by zandbelt** [comment]
2nd batch that completes the help texts was pushed upstream and to the master branch; those will be deployed with the next release
