### ISSUE TITLE
Checkbox needed on configuration pages to select form post response mode tests

### ISSUE THREAD

**Issue by selfissued** [openid-certification/oidctest#76]
A checkbox is needed on the configuration pages to select form post response mode tests.  It would be added to pages like this one: https://op.certification.openid.net:60046/pedit - probably either before or after the Cryptographic support section.  When enabled, this checkbox would cause the form post response mode tests to be shown and those not relevant to this new certification profile not to be shown.

**Comment by zandbelt** [comment]
part of released 2.0.11; the checkbox is added now; the requirements for the form_post profile will be reviewed in another ticket
