### ISSUE TITLE
500 Internal Server Error from test OP-request_uri-Support

### ISSUE THREAD

**Issue by selfissued** [openid-certification/oidctest#77]
Go to the URL https://op.certification.openid.net:60046/OP-request_uri-Support and you'll see this output:

500 Internal Server Error
request_uri parameter not supported

Powered by CherryPy 8.9.1

**Comment by zandbelt** [comment]
It appears this is the way that the tool reports that `request_uri_parameter_supported` is set to `False` in the Discovery document, see: https://github.com/openid-certification/otest/blob/master/src/otest/verify.py#L51

**Comment by selfissued** [comment]
This makes it appear that the test tool is broken and doesn't result in a log entry.  Can we change this soon to report the error in the normal way?

**Comment by zandbelt** [comment]
@selfissued we can catch the Break exception here https://github.com/openid-certification/otest/blob/master/src/otest/aus/tool.py#L115 so that a log entry is produced but the test result is still/always "PARTIAL RESULT"; it would be better to change that into ERROR; how to do that?

**Comment by rohe** [comment]
A quick look gave me the idea that we could replace:

            except ConditionError:
                pass

With

            except ConditionError as err:
                self.conv.events.store(
                    EV_CONDITION,
                    State(test_id=test_id, status=ERROR, message=err,
                          context='verify'))

it should be enough, but I have to look a bit closer to be sure that that is what we should do.

**Comment by selfissued** [comment]
Please do something.  Currently it just looks like our service is broken.

**Comment by zandbelt** [comment]
rolled out as part of OP 2.0.13; instances would need to be restarted to pickup the changes
