### ISSUE TITLE
The page with the list of tests for RP certification is not shown

### ISSUE THREAD

**Issue by vnikolaou** [openid-certification/oidctest#79]
I am trying to open the : 

https://rp.certification.openid.net:8080/gluu/list?profile=C  

but gives an error : 

FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/oidf/oidc_cp_rplib/flows/list.json'

**Comment by zandbelt** [comment]
I'm not sure where the link you provide is generated from but to list the tests for that profile you should use: https://rp.certification.openid.net:8080/list?profile=C

**Comment by vnikolaou** [comment]
Yes you are right. THank you
