### ISSUE TITLE
Test Environment Maintains State Across Flows

### ISSUE THREAD

**Issue by sjudson** [openid-certification/oidctest#8]
In the old environment, when changing the flow the suite of tests was reset. The new test environment does not, and instead maintains state on whatever tests apply to both flows. This could possibly be misleading, and cause tests to not be run to completion.

For instance, switching from `id_token token` to `code id_token token` gives:

![openid_env_state](https://cloud.githubusercontent.com/assets/20324824/25407556/b8132fe2-29d8-11e7-8eeb-f3ed46170859.jpeg)

with the ID Token tests which apply to both already showing green, despite not having been run for the latter.

**Comment by rohe** [comment]
Cleans state now.

**Comment by zandbelt** [comment]
@sjudson can you confirm this works for you so we can close it?

**Comment by zandbelt** [comment]
My testing makes me believe this is fixed.
