### ISSUE TITLE
Error in Test OP-claims-essential

### ISSUE THREAD

**Issue by marsangr** [openid-certification/oidctest#81]
I refer to the results of the aforementioned test here
https://op.certification.openid.net:60381/test_info/OP-claims-essential

The test queries the userinfo-Endpoint of the OP and is able to follow the references (via distributed claims) to the upstream claims providers. However after issuing the final query

`url:https://iagent.freedom-id.de/user-info-endpoint status_code:200`

the result shown is NOT the real answer of that endpoint, but a JSON conflating the answer of the OP-userinfo-Endpoint and the answer of the upstream claims provider.

Thus, the final warning

`verify-claims: status=WARNING, message=Unexpected claims in response: ['_claim_sources', '_claim_names']`

is a mistake.

**Comment by marsangr** [comment]
It seems to be a systematic error, also present in the tests

(OP-scope-All)
(OP-scope-address)
(OP-scope-email)
(OP-scope-phone)
(OP-scope-profile)

**Comment by zandbelt** [comment]
https://github.com/OpenIDC/pyoidc/commit/3002d1b02bb662d6496a9483dd53a214d296a17c

**Comment by zandbelt** [comment]
The "remove unexpected claims `__claims_sources` and `_claim_names`"  feature is now rolled out on production as part of [OP release 2.0.14](https://github.com/openid-certification/oidctest/releases/tag/v1.0.17). @marsangr please confirm.

**Comment by marsangr** [comment]
Now I am able to pass the test, so there's improvement, but the display of the tool is not correct:

The "_claims_sources" and "_claim_names" are removed from all userinfo-responses. So it looks like 

6.069 | http response | url:https://auth.freedom-id.de/userinfo status_code:200
-- | -- | --
6.069 | OpenIDSchema | {     "name": "Value of name",     "sub": "4AOKNFYHf55AXmbmr9VLuoQ2+x0AtXsKe6m3m5Vxlei+1gh6tJLeXnt76MAGfcXd" }

which is definitely not correct.

That Userinfo-Endpoint delivers _claims_sources and _claims_names
and https://iagent.freedom-id.de/user-info-endpoint is the claims source that
delivers the values.

**Comment by zandbelt** [comment]
You mean that "_claim_sources" and "_claim_names" are stripped from *every* userinfo response so the distributed claims are never resolved? If so it looks like an issue in pyoidc...

**Comment by marsangr** [comment]
For me it looks like if the answer of all userinfo endpoints are stored in the same local variable. So first we have the "_claim_sources" and "_claim_names" in it (answer of the IdP userinfo endpoint), then the code resolves the distributed claims (answer of the Claims Provider), adds them to the variable, and then deletes the "_claim_sources" and "_claim_names" from it. At the end it looks as if all answers looked like the final state of that local variable.

I am not going to say that's an issue in pyoidc, maybe it's a problem of misunderstanding their API. In any case, what the OIDC-Testtool shows

6.069 | http response | url:https://auth.freedom-id.de/userinfo status_code:200
-- | -- | --
6.069 | OpenIDSchema | {     "name": "Value of name",     "sub": "4AOKNFYHf55AXmbmr9VLuoQ2+x0AtXsKe6m3m5Vxlei+1gh6tJLeXnt76MAGfcXd" }

is wrong. That's not the answer of that endpoint. That endpoint only returns  "_claim_sources" and "_claim_names"

**Comment by zandbelt** [comment]
We're closing this because the original issue was solved in 2.0.14; if you think logging is lacking you're welcome to open a different issue.
