### ISSUE TITLE
Error in the registered request_uris of the client for test OP-request-Unsigned

### ISSUE THREAD

**Issue by marsangr** [openid-certification/oidctest#82]
The aforementioned test

https://op.certification.openid.net:60381/OP-request-Unsigned

registers a client with the request_uris set to the following value:

"https://op.certification.openid.net:60381/requests/d3c028cd6365e599cae284c290a3b9875ee930ee535e19c423b70b9f7c320571#dV7jQrUZcVIy7NJP"

The content of the request stored at that URI has the client_id "ovk6fe7bcsjke", however, the authentication request actually sent to the OP has a different client_id parameter.

**Comment by panva** [comment]
`OP-request-Unsigned` is not providing a URL Referenced Request Object via `request_uri`. The request_uri registration might as well be skipped for this test.

**Comment by marsangr** [comment]
I agree. That's more just of a cosmetic matter.

**Comment by marsangr** [comment]
However, the test still fails leaving absolutely no logs to go through. Could you please check it?
https://op.certification.openid.net:60381/OP-request-Unsigned

**Comment by panva** [comment]
I can see nothing out of the ordinary in the request it is making to your `authorization_endpoint`.

However the endpoint just throws and no callback ever arrives to the specified `redirect_uri`.

```js
{
  "error": "invalid_request",
  "error_description": "Invalid request: The client registration requires request_uri / request parameter"
}
```

I'd like to point out that neither `require_request_uri_registration` in the discovery nor actually dynamically registering with `request_uris` is related to the `request` parameter and this request should be accepted.

**Comment by marsangr** [comment]
Following up this behaviour with our software vendor (that have a certified product themselves). Please don't close until clarified.

**Comment by marsangr** [comment]
Problem solved. Request parameter wasn't being dealt with properly server-side. Sorry for the confusion.
