### ISSUE TITLE
(OP-Req-id_token_hint) different nonce

### ISSUE THREAD

**Issue by lroman2025** [openid-certification/oidctest#85]
In second authentication request differnt nonce is sent, so previously generated id_token is not valid. Why test assumes that id_token would be valid, when different nonce was sent?

**Comment by panva** [comment]
The nonce sent is not related to ones from previous requests. id_token_hint nonce shouldn't be validated for neither nonce presence nor value

**Comment by selfissued** [comment]
There is no requirement that the ID Token used for the id_token_hint contain the same nonce as the request.  In fact, this would be impossible to arrange for in most cases.  Certainly, the nonce shouldn't be reused.

We will close this on the next call unless additional information comes to light.

**Comment by selfissued** [comment]
Given that no additional information has been provided, we're closing this with no action.
