### ISSUE TITLE
OP-request-Unsigned shouldn't register request_uris

### ISSUE THREAD

**Issue by yv13** [openid-certification/oidctest#87]
The OP-request-Unsigned test registers a client with a request_uri, but doesn't make use of the `request_uri` parameter when making the actual OpenID authentication request.

```
response_type=code&request=eyJhbGciOiJub25lIn0.eyJyZXNwb25zZV90eXBlIjogImNvZGUiLCAibm9uY2UiOiAiQTVIWHFES1RjZG5vNGgzdCIsICJzdGF0ZSI6ICI4bUt0YmEwajRzZ2xoTXJsIiwgImNsaWVudF9pZCI6ICJyb2tzZmtlcWgzaHNnIiwgInJlZGlyZWN0X3VyaSI6ICJodHRwczovL29wLmNlcnRpZmljYXRpb24ub3BlbmlkLm5ldDo2MTE2Ny9hdXRoel9jYiIsICJzY29wZSI6ICJvcGVuaWQifQ.&nonce=A5HXqDKTcdno4h3t&redirect_uri=https%3A%2F%2Fop.certification.openid.net%3A61167%2Fauthz_cb&scope=openid&state=8mKtba0j4sglhMrl&client_id=roksfkeqh3hsg
```

This will cause the request to fail with OpenID provider servers which implement software statements, as per https://tools.ietf.org/html/rfc7591#section-2.3 . The software statement is a method to lock down a client's registration to a certain set of parameters, and enforce their usage. A server that implements software statements with `request_uris` will expect the RP to use a registered request URI, and if none is submitted, the request will fail.

The registered request URI also points to a JWT with client_id that doesn't match the registered:

https:\/\/op.certification.openid.net:61167\/requests\/2c042ac070e1560311a1d519572677bf1fc20e92393cf56260d68171c217ddc4#ZE2yVfE0Dy4skNvS

The JWT:

```
eyJhbGciOiJub25lIn0.eyJyZXNwb25zZV90eXBlIjogImNvZGUiLCAibm9uY2UiOiAiWERKTnBQREpRRGJvVklDZSIsICJzdGF0ZSI6ICJINTdHMEtmNkp1NzRoQzVNIiwgImNsaWVudF9pZCI6ICJiZHpxemhudmNiaGNpIiwgInJlZGlyZWN0X3VyaSI6ICJodHRwczovL29wLmNlcnRpZmljYXRpb24ub3BlbmlkLm5ldDo2MTE2Ny9hdXRoel9jYiIsICJzY29wZSI6ICJvcGVuaWQifQ.
```

The JWT claims:

```
{
  "response_type": "code",
  "nonce": "XDJNpPDJQDboVICe",
  "state": "H57G0Kf6Ju74hC5M",
  "client_id": "bdzqzhnvcbhci",
  "redirect_uri": "https://op.certification.openid.net:61167/authz_cb",
  "scope": "openid"
}
```

**Comment by zandbelt** [comment]
I don't see why implementation of software statements matters here: software statements are not used by the OP test tool and are not part of the certification suite. Can you elaborate?

**Comment by selfissued** [comment]
The test OP-request-Unsigned uses the "request" parameter - not the "request_uri" parameter, so it's not clear what the actual issue is here.  Can you elaborate?
