### ISSUE TITLE
OP and RP tests use/expect non-conform client_secret_basic format

### ISSUE THREAD

**Issue by panva** [openid-certification/oidctest#88]
There's a problem with the way client_secret_basic client authentication is sent (OP tests) and checked (RP tests).

> https://tools.ietf.org/html/rfc6749#section-2.3.1
> Clients in possession of a client password MAY use the HTTP Basic authentication scheme as defined in [RFC2617] to authenticate with the authorization server. The client identifier is encoded using the "application/x-www-form-urlencoded" encoding algorithm per Appendix B, and the encoded value is used as the username; the client password is encoded using the same algorithm and used as the password.

> https://tools.ietf.org/html/rfc6749#appendix-B

```
   For example, the value consisting of the six Unicode code points
   (1) U+0020 (SPACE), (2) U+0025 (PERCENT SIGN),
   (3) U+0026 (AMPERSAND), (4) U+002B (PLUS SIGN),
   (5) U+00A3 (POUND SIGN), and (6) U+20AC (EURO SIGN) would be encoded
   into the octet sequence below (using hexadecimal notation):

     20 25 26 2B C2 A3 E2 82 AC

   and then represented in the payload as:

     +%25%26%2B%C2%A3%E2%82%AC
```

Given the following client_id and client_secret:

```
id: 796d8fae-a42f-4e4f-ab25-d6205b6d4fa2
secret: MKEM/A7Pkn7JuU0LAcxyHVKvwdczsugaPU0BieLb4CbQAgQj+ypcanFOCb0/FA5h
```

The Authorization header should be

```
Authorization: Basic Nzk2ZDhmYWUtYTQyZi00ZTRmLWFiMjUtZDYyMDViNmQ0ZmEyOk1LRU0lMkZBN1BrbjdKdVUwTEFjeHlIVkt2d2RjenN1Z2FQVTBCaWVMYjRDYlFBZ1FqJTJCeXBjYW5GT0NiMCUyRkZBNWg=

// 796d8fae-a42f-4e4f-ab25-d6205b6d4fa2:MKEM%2FA7Pkn7JuU0LAcxyHVKvwdczsugaPU0BieLb4CbQAgQj%2BypcanFOCb0%2FFA5h
```

but is currently 
```
Authorization: Basic Nzk2ZDhmYWUtYTQyZi00ZTRmLWFiMjUtZDYyMDViNmQ0ZmEyOk1LRU0vQTdQa243SnVVMExBY3h5SFZLdndkY3pzdWdhUFUwQmllTGI0Q2JRQWdRait5cGNhbkZPQ2IwL0ZBNWg=

// 796d8fae-a42f-4e4f-ab25-d6205b6d4fa2:MKEM/A7Pkn7JuU0LAcxyHVKvwdczsugaPU0BieLb4CbQAgQj+ypcanFOCb0/FA5h
```

To use the value `" %&+£€"` (minus the " - md formatter) from the spec as both id and secret the header should be (don't mind the fact that it doesn't follow *VSCHAR client-id and client-secret syntax)
```
Authorization Basic KyUyNSUyNiUyQiVDMiVBMyVFMiU4MiVBQzorJTI1JTI2JTJCJUMyJUEzJUUyJTgyJUFD

// +%25%26%2B%C2%A3%E2%82%AC:+%25%26%2B%C2%A3%E2%82%AC
```

I've just recently gotten around to fix this in both my op and rp libraries and the certification suite is failing.

**Comment by selfissued** [comment]
Roland - is the certification suite form-url-encoding and form-url-decoding the pair of "Authorization Basic" values when used, as specified in https://tools.ietf.org/html/rfc6749#section-2.3.1 or is it omitting that step?  If so, we need to fix the certification test suite to do so.

The problem is that for alphanumeric Client ID and Client Secret values, things will appear to work fine but it will fail for special characters that are transformed by the form-url-encoding.

**Comment by rohe** [comment]
I'll check tomorrow and will fix if it's not as it should be.

**Comment by zandbelt** [comment]
https://github.com/OpenIDC/pyoidc/commit/c8b60d6194b5b1bb8a223cacf0e550ca18332a56

**Comment by zandbelt** [comment]
The "form-url-encoded client secret" feature is now rolled out on production as part of [OP release 2.0.14 and RP release 1.0.10](https://github.com/openid-certification/oidctest/releases/tag/v1.0.17). @panva please confirm.

**Comment by panva** [comment]
👍
