### ISSUE TITLE
token_type response parameter checks

### ISSUE THREAD

**Issue by zandbelt** [openid-certification/oidctest#89]
Wrt. to the `token_type` parameter in the authentication response we could do 2 things:
- handle the case when `token_type` is missing from the response and throw an appropriate error
- write a test for `token_type` parameter existence since it is a required parameter

**Comment by panva** [comment]
+1 for writing a test for token_type parameter existence and value

**Comment by zandbelt** [comment]
added a PR for this test to Roland's repo: https://github.com/rohe/oidctest/pull/108

**Comment by zandbelt** [comment]
we're ditching the PR with the new `token_type` test, see: https://github.com/rohe/oidctest/pull/108#issuecomment-417946995

 I'll add some code shortly to verify (all) regular responses.

**Comment by zandbelt** [comment]
It appears that for flows where the access token is retrieved on the backchannel, the token_type parameter existence is already checked in pyoidc, see: https://github.com/OpenIDC/pyoidc/blob/v0.14.0/src/oic/oauth2/message.py#L1073

for Implicit/Hybrid I've added it here:
https://github.com/OpenIDC/pyoidc/pull/565

**Comment by zandbelt** [comment]
https://github.com/OpenIDC/pyoidc/pull/565 was merged and this will be included in the next release of pyoidc > 0.14.0

**Comment by zandbelt** [comment]
this was deployed just now as part of OP 2.2.1 https://github.com/openid-certification/oidctest/releases/tag/v1.2.0
