### ISSUE TITLE
https://new-op.certification.openid.net:60000/ not enabled

### ISSUE THREAD

**Issue by selfissued** [openid-certification/oidctest#9]
On the current OP site we instruct people to go to https://op.certification.openid.net:60000/.  We should enable https://new-op.certification.openid.net:60000/ now so that when we switch the domain names, the current (https) configuration URL will keep working.

**Comment by zandbelt** [comment]
+1, I also believe we should combine this with cloning the stable branch of the certification code to the test server rather than @rohe 's branch and use released versions of pyjwkest and pyoidc.

**Comment by zandbelt** [comment]
that is done just now by changing `config.py` and restarting the config server with the `-t` flag added to `run.sh`
