### ISSUE TITLE
factor out fedoidc dependency

### ISSUE THREAD

**Issue by zandbelt** [openid-certification/oidctest#90]
The `fedoidc` project is a dependency for `oidctest` today whereas in fact it should be a separate component that is not a dependency.

**Comment by rohe** [comment]
I've modified oidctest, removing all the fedoidc dependencies.
Please verify!

**Comment by zandbelt** [comment]
In which repo is this?

**Comment by rohe** [comment]
I just pushed it :-/

**Comment by selfissued** [comment]
Fixed and deployed
