### ISSUE TITLE
[OP tests w/discovery] wrong require_request_uri_registration assumed

### ISSUE THREAD

**Issue by panva** [openid-certification/oidctest#93]
When not provided in OP discovery `require_request_uri_registration` value [should](https://openid.net/specs/openid-connect-discovery-1_0.html) default to `false`, currently this falls back to `true` in the OP tests.

this is apparent from the log line about discovery results when this value is not included

**Comment by selfissued** [comment]
Hans will fix this

**Comment by zandbelt** [comment]
merged into pyoidc master(https://github.com/OpenIDC/pyoidc/commit/69a7ef59c1f40c29313354e034bc15bfff92921b)  but requires a new release of pyoidc

**Comment by zandbelt** [comment]
this was deployed just now as part of OP 2.2.1 https://github.com/openid-certification/oidctest/releases/tag/v1.2.0
