### ISSUE TITLE
Test fails with `NoSuitableSigningKeys:No key with kid` but the kid is supplied

### ISSUE THREAD

**Issue by aeneasr** [openid-certification/oidctest#94]
I run a deployment which fails at `OP-IDToken-C-Signature` with the error message

>AccessToken:OP-IDToken-C-Signature: status=ERROR, message=No key with kid: public:fa4482ea-ceaa-438c-8f6f-9cac77693252

The ID Token is

```
eyJhbGciOiJSUzI1NiIsImtpZCI6InB1YmxpYzpmYTQ0ODJlYS1jZWFhLTQzOGMtOGY2Zi05Y2FjNzc2OTMyNTIiLCJ0eXAiOiJKV1QifQ.eyJhdWQiOiJ0ZXN0LWNsaWVudCIsImF1dGhfdGltZSI6MTUyNjc1OTM2MiwiYmF6IjoiYmFyIiwiZXhwIjoxNTI2NzYzNDIzLCJpYXQiOjE1MjY3NTk4MjMsImlzcyI6IiIsIm5vbmNlIjoiWUhLZDNoUHBleXNqQXVVMCIsInJhdCI6MTUyNjc1OTgyMSwic3ViIjoiZm9vQGJhci5jb20ifQ.Ih9wx3X0BgvktEoIqIeHYpDcf3mKvhNXdDXRfGNS8gPRV045TYN92RYmqXLnF7bxBy-X0clKGwXiZulnO03nxmJgDBU2CAzSKCJqylCiWQjDthFFjNQfDWHvexQ8hfNxgJn3FG1KGh5qPQiL7yOe-tfrORrvBvCkwDHY5rSglSLvDd69pv-i43CS10u8TD-hDK2xAjnCT0ktR_Cfn14RRPJdARK8jl66iNCJD-j1kpNph0rTmwaTOvHoeZItwStD4YesjIO1kvB1ahr8H4r9ytnzb4Mg36oTkI9sU89rorxDu3SkoK6W8RJsoKuM828Mp78kPTdoJmD6awPOPCrfJWc9Tl8YZKB---34KZU9jcyo3bLNQbyEwrq0qamaZwZ4p6oq1UvYt_G4WxWB42_lwUoWkot09WOPITeD-ffnRF80-d6rY-oanAcTZ9aPXnFt7mjL58wAUfkpJ4Pbs6wgOTfcKdJMvgrFCcHsqO0_OQ3T-966f8UbYSxoipBjM7QawW_gmuU8ipOFYj1ScoWWUO7OZx6N1QHaMZl4s-NrVVRBOiG3g7thgoo6_PT5yaUC2jkI1aaFrtDrO86GyRtWz_KwhzyqGY04FXARSf0beLoMcuqfJ7zugaMgy71HXIPsm3yDDilTzHTRrdQK-CRtI2H_ttFteb8hJyZriNi-wVM
```

with header

```
{
  "alg": "RS256",
  "kid": "public:fa4482ea-ceaa-438c-8f6f-9cac77693252",
  "typ": "JWT"
}
```

So the kid is detected properly here. What is weird though is that the jwks.json endpoint has that exact key:

![image](https://user-images.githubusercontent.com/3372410/40272598-3cdcc68e-5bb0-11e8-995e-7a913fe975d3.png)

so I'm wondering why this fails? Could it be due to the `:` in the ID?

**Comment by arekkas** [comment]
Just to make sure, the discovery tests run smoothly:

![image](https://user-images.githubusercontent.com/3372410/40272614-84e411d0-5bb0-11e8-8bae-f2be0181cfb3.png)

**Comment by arekkas** [comment]
Other libraries apparently require `"use": "sig"` to be set in order to find the signing key which was not the case. I fixed that

![image](https://user-images.githubusercontent.com/3372410/40272828-981f2c90-5bb4-11e8-9d49-3ec7c3c13f1f.png)

and now libraries such as [jwks-rsa](https://github.com/auth0/node-jwks-rsa) are able to validate the ID Token issued by the AS. However, the OIDC test is still not able to do so.

**Comment by arekkas** [comment]
The issue was that the `iss` value was not set in the ID Token. I think the error message should point to the actual error. I found the cause by googling and found someone else who had that issue.

**Comment by selfissued** [comment]
We should enhance the error handling for this case so that the "iss" claim being missing results in an error message saying so.  Roland says that this is a reasonably common mistake.

**Comment by rohe** [comment]
I'm Issuing an RP for pyoidc. Because it's there we need the checking.

**Comment by zandbelt** [comment]
https://github.com/OpenIDC/pyoidc/pull/549

**Comment by zandbelt** [comment]
this was deployed just now as part of OP 2.2.1 https://github.com/openid-certification/oidctest/releases/tag/v1.2.0
