### ISSUE TITLE
OP-Req-id_token_hint is not sending an id_token_hint parameter

### ISSUE THREAD

**Issue by selfissued** [openid-certification/oidctest#98]
If you look at the log https://op.certification.openid.net:61283/test_info/OP-Req-id_token_hint you'll see that the request does not include an id_token_hint parameter.  Thus, it seems that the id_token_hint functionality of OPs is not currently being tested.  Kim Cameron noticed this too while testing.

Hopefully this can be fixed pronto, as it's a huge omission in the test coverage!

**Comment by panva** [comment]
Must be a regression like #92

**Comment by panva** [comment]
first request to obtain an id token, then a second containing a hint. Looks fine to me actually.

**Comment by selfissued** [comment]
My mistake.  I must have only been looking at the first authentication request.
