### ISSUE TITLE
OP-OAuth-2nd-Revokes instructions incorrect

### ISSUE THREAD

**Issue by selfissued** [openid-certification/oidctest#99]
Kim Cameron made the following observation while testing.  Do you agree that the instructions displayed in the UI are incorrect?  If so, what should they be changed to saying?

As far as the test “Trying to use authorization code twice should result in revoking previously issued access tokens” (one of the last tests) goes, the message given when running it is quite wrong:

This test should result in the OpenID Provider displaying an error message in your user agent. You should ignore the status of this test in the test tool, since it will be incomplete. You must submit a screen shot of the error shown as part of your certification application.

In fact as I see it, the if there is a second attempt to use the authorization code an error should be issued – for example:
```
 { 
    "error": "access_denied", 
    "error_description": "The resource owner or authorization server denied the request.: access_token is invalid" 
}
```
If you do so you do get a green check mark, but the verbiage above about “error message in your user agent” is incorrect in my view.  Such a message would be given by the RP on receipt of the error response.

**Comment by selfissued** [comment]
Hans will correct this to say that it should result in an OAuth error being returned.

**Comment by zandbelt** [comment]
deployed as part of OP version 2.1.2 now
